### ISSUE TITLE
Improvement suggestion - Adding Crash analytics to apps using Swift

### ISSUE THREAD

**Issue by laurigardner** [mixpanel/mixpanel-swift#114]
Currently: Crash analytics are not recorded by Mixpanel. Instead we have to use another 3rd party solution like HockeyApp to record crashes. We then have to aggregate the two streams of information in Kilpfolio.

Wish: To have crashes as part of the Mixpanel "package".

**Comment by yarneo** [comment]
Thanks @laurigardner for your suggestion. When you ask for Crash analytics, would indicating that there was a crash and to what user be sufficient. Or are you looking for a more complete crash reporting tool that includes stack trace with symbolication?

If the former is what you are looking for, our Objective-C SDK currently has crash reporting if you turn on "Automatically collect common mobile events" in the Autotrack tab under Project Settings.

**Comment by laurigardner** [comment]
Hi Yarden,

You mention Objective-C SDK currently has crash reporting, can you confirm that it’s available for the Swift programming language?

According to an FAQ, this is only available for android platforms and not for iOS.

Regards,

-Lauri

Lauri Gardner
Global Support Manager | roOom<https://rooomy.com/>y<https://rooomy.com/>®
+1 669.238.8886

**Comment by yarneo** [comment]
Yes, our Objective-C SDK works with Swift projects as well. Apologies for the confusion in the documentation. Here you can see what automatically collected events (including App Crashed): https://mixpanel.com/help/questions/articles/which-common-mobile-events-can-mixpanel-collect-on-my-behalf-automatically
