### ISSUE TITLE
Push notifications is not tracked in iOS 10 (new UserNotifications framework)

### ISSUE THREAD

**Issue by andschdk** [mixpanel/mixpanel-swift#115]
The current doc states:
> Push open tracking is automatically available in v2.1.9 in Swift.

**However this is not the case for iOS 10, because of the new UserNotifications framework.**

Currently the old functions from `UIApplicationDelegate` is replaced using swizzling. Because these functions are never called in iOS 10 the auto tracking feature fails.
Maybe it could be solved in a similar way but instead of using `UIApplication.shared.delegate` one should use `UNUserNotificationCenter.current().delegate`. It will be a bit more tricky tough.

Support Engineer Marie Atterbury pointed me in a direction for a possible workaround (thanks for that Marie 👍 ). One can basically track the events manually by copying the track function from the SDK:

```swift
extension MixpanelInstance {

    /// Copied from MixpanelInstance
    ///
    /// - Parameters:
    ///   - userInfo: userInfo from the notification
    ///   - event: The mixpanel event name
    func trackPushNotification(_ userInfo: [AnyHashable: Any],
                               event: String = "$campaign_received") {
        if let mpPayload = userInfo["mp"] as? InternalProperties {
            if let m = mpPayload["m"], let c = mpPayload["c"] {
                var properties = Properties()
                for (key, value) in mpPayload {
                    if key != "m" && key != "c" {
                        // Check Int first, since a number in the push payload is parsed as __NCSFNumber
                        // which fails to convert to MixpanelType.
                        if let typedValue = value as? Int { properties[key] = typedValue }
                        if let typedValue = value as? MixpanelType { properties[key] = typedValue }
                    }
                }
                properties["campaign_id"]  = c as? Int
                properties["message_id"]   = m as? Int
                properties["message_type"] = "push"
                track(event: event,
                      properties: properties)
            } else {
                // malformed mixpanel push payload
            }
        }
    }
}
```
I'm still confused about where and what to track as your events are better suited the old API. Or maybe it is the names that confuses me:

**$app_open** 
marks notification as opened and is only used for push tracking right?
Why is it not tracked each time the app opens? (without properties ofc)

**$campaign_received**
marks notification as opened, which I don't understand because it is tracked in `didReceiveRemoteNotification`which means a push will be treated as opened just because it was received?

**$campaign_open** 
not sure what this does to the report

Looking at the new API we have:

```swift
public func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    // Notification will be displayed
}
```

```swift
public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {

    if response.actionIdentifier != UNNotificationDismissActionIdentifier {
        // User opened the notification from some action other than UNNotificationDismissActionIdentifier. This is both for a launching app and an already launched app.
    }

    completionHandler()
}
```

Before tracking events manually I need some more clarification for the questions above.
Please correct me if I am wrong in any statements above.

_I see this as a high-priority issue because the vast majority of users are using iOS10 thereby invalidating any reports involving push open tracking. As a quick-fix the documentation should be updated with a detailed workaround._

**Comment by andschdk** [comment]
Just noticed that if not setting `UNUserNotificationCenter.current().delegate = self` the old deprecated functions are used. 
As more and more apps will use the new framework this issue will become more relevant.

**Comment by yarneo** [comment]
Hey @andschdk , thank you for writing in! 
We have now added automatic Mixpanel push tracking support to the new UNUserNotificationCenter framework in our latest release (v2.2.1).

In terms of deprecation, you are indeed correct that `application:didReceiveRemoteNotification:` is deprecated, but `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` is still alive and kicking, and allows users to track received pushes if they also have customers with pre-iOS10 operating systems on their device.

Let me know if the fix works well for you or if there is anything else I can help you with!

**Comment by andschdk** [comment]
Hi @yarneo 
Thanks for your quick response. However I face some problems with the release.
I opened a new issue #119
