### ISSUE TITLE
Library using non extension safe API

### ISSUE THREAD

**Issue by mxcl** [mixpanel/mixpanel-swift#116]
<img width="973" alt="screen shot 2017-08-04 at 12 32 04 pm" src="https://user-images.githubusercontent.com/58962/28977672-015485d4-7911-11e7-989a-b98394ab0b28.png">

This is 2.19 and 2.2.0.

**Comment by yarneo** [comment]
Apologies for that @mxcl , we will be more mindful in future releases to the App Extension consolidation workaround we introduced. The new release should fix this issue.

**Comment by mxcl** [comment]
Thanks!
