### ISSUE TITLE
Notification open rate is only tracked when app is in foreground. (UserNotifications framework)

### ISSUE THREAD

**Issue by andschdk** [mixpanel/mixpanel-swift#119]
With the new 2.2.1 release, automatic push notification tracking should work with the new UserNotifications framework.

My initial test resulted in notifications only being tracked as opened when the app was in foreground (presenting the push notification)

Looking at the diff it looks like only 
```swift
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
``` 
is being swizzled.

This function is only called when the app is in foreground
>Apple doc:
> _The method will be called on the delegate only if the application is in the foreground. [...]_

I would expect all cases to track a push open and not only when the app is in foreground:

Opened from state | Tracked
------------ | -------------
Active/Foreground | YES
Background/Suspended | YES
Not running | YES

So to conclude, currently it looks like this:

Opened from state | Tracked
------------ | -------------
Active/Foreground | YES
Background/Suspended | NO
Not running | YES (tracked using `Mixpanel.initialize(token: "token-here", launchOptions: launchOptions)`

**Comment by yarneo** [comment]
Hi @andschdk , unfortunately I was aware that this method only allows foreground tracking, it's a shame. I think one thing we can do is swizzle also the other method (https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter) but looks like that method is more intended for tracking actions that were selected in a notification.

For the "Not running" scenario, we fetch the payload from the launchOptions in: `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool` as seen here: https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/MixpanelInstance.swift#L268
So when initializing Mixpanel have it receive the launchOptions and it will receive the push payload and track it if it's a mixpanel push.

**Comment by andschdk** [comment]
Hi @yarneo , 
I must have missed the `initialize` part of Mixpanel. From day one we have been initializing the SDK using the default initializer. Maybe the developer doc should be updated to include info about that especially in regards to auto tracking (https://mixpanel.com/help/reference/swift).

I will update the table (and original description):
Opened from state | Tracked
------------ | -------------
Active/Foreground | YES
Background/Suspended | NO
Not running | YES

I agree with you that the _Background_ case is a hard to solve 😕 
Swizzling `userNotificationCenter(_:didReceive:withCompletionHandler:)` may lead to other issues.

**Comment by andschdk** [comment]
We are currently experimenting with tracking push opens manually in
```swift
func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)
```
and nowhere else. This is tracked for all scenarios.

We are not able to track the $app_open event, but we are just interested in the open rate so we only use $campaign_received. 

I know this only works because we are targeting iOS10+ and only using the new framework.

**Comment by yarneo** [comment]
The new solution I have added is to swizzle `userNotificationCenter(_:didReceive:withCompletionHandler:)` instead. this means that we will track when a push notification is actually pressed, but also for background modes. I am fairly happy with this solution because it is more inline with tracking actual direct push opens. This is now on the master branch, feel free to check it out and ill try to send a release by end of week.

**Comment by andschdk** [comment]
@yarneo I agree with you that this is better.

Have you made any thoughts on the actual events names, will you continue with:
> $app_open
> $campaign_received

One thing I noticed is that a push notification is tracked twice when opening from a "Not running" application when initialising Mixpanel with `launchOptions`. However, looking at the report in the frontend something is taking care of it, because here it is only tracked as a single "open". 
That being said both events are tracked simultaneously ($app_open, $campaign_received). That might need some attention?

I think the **$app_open** event is weird. In regards to tracking and analytics why does it makes sense to differentiate between an app being launched (not running) and an app being opened from background (from a notification)...?

**Comment by andschdk** [comment]
@yarneo it has been a while since your last comment on this. What is the status? 
The current release is not tracking properly.

**Comment by yarneo** [comment]
Hi @andschdk , thanks for the reminder. 
We don't have any plans to change the current event naming as that would require additional work on the backend. 

But good news, in terms of UNUserNotifications the fix is already on master and i will try to get a release out early next week!

**Comment by andschdk** [comment]
@yarneo what about the "double tracking" mentioned in my previous comment?

Have you considered an opt-out feature, to enable one to disable the push auto tracking while still having "auto track" enabled in project settings?

**Comment by yarneo** [comment]
If it is only showing once in the UI as you said, then the data presented is valid and I am not too worried about it.

We aren't going to put time currently in consolidating both events, even though it is something we would like to eventually do and is already in our backlog.

Thanks

**Comment by justinHowlett** [comment]
@yarneo any updates on this? Do you have a planned release eta that includes this fix?

**Comment by yarneo** [comment]
Let me know if the latest release helps resolve your issues using the UserNotifications framework. thanks!

**Comment by RuiAAPeres** [comment]
We can confirm that this is still an issue for us with version: `Mixpanel-swift (2.3.2)`

**Comment by mluisbrown** [comment]
Adding to what @RuiAAPeres said, just removing the call to `setupAutomaticPushTracking` in `AutomaticEvents.swift` solves our problem. 

That is, our `UNUserNotificationCenterDelegate` implementation is called, regardless of whether the app is running in background or not.

With the current Mixpanel code, in the scenario of "notification received when app not running", neither the swizzled Mixpanel method:

```swift
@objc func userNotificationCenter(_ center: UNUserNotificationCenter,
                                  newDidReceive response: UNNotificationResponse,
                                  withCompletionHandler completionHandler: @escaping () -> Void)
```

nor the original delegate implementation is called.

There is something wrong with the way the swizzling is done which breaks this scenario (app not running when notification is received). If the app is running in background or foreground, there is no problem.

In addition, I would recommend that the enabling of automatic events should be configurable via an initialisation option. As it is not, our only solution was to fork this repo and remove the call to `setupAutomaticPushTracking`.

**Comment by zihejia** [comment]
We will close this one and any further discussion to this issue, please go to the new one: https://github.com/mixpanel/mixpanel-swift/issues/201
