### ISSUE TITLE
Not swizzling delegate functions correctly for UNUserNotificationCenter.current

### ISSUE THREAD

**Issue by andschdk** [mixpanel/mixpanel-swift#122]
The log:
```
[Mixpanel - Swizzle.swift - func swizzleSelector(_:withSelector:for:name:block:)] (error) - Swizzling error: Cannot find method for userNotificationCenter:willPresentNotification:withCompletionHandler: on NotificationManager
```

Where `NotificationManager` is implementing `UNUserNotificationCenterDelegate` and setting:
```swift
UNUserNotificationCenter.current().delegate = self
```

**Comment by andschdk** [comment]
I see that you find the "selector" from the new `UNUserNotificationCenter.current`, but it still looks like you are passing the app delegate as argument to the swizzling function: https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/AutomaticEvents.swift#L199

The log:
```
[Mixpanel - Swizzle.swift - func swizzleSelector(_:withSelector:for:name:block:)] (error) - Swizzling error: Cannot find method for userNotificationCenter:willPresentNotification:withCompletionHandler: on NotificationManager
```

Where `NotificationManager` is implementing `UNUserNotificationCenterDelegate` and setting:
```swift
UNUserNotificationCenter.current().delegate = self
```

**Comment by yarneo** [comment]
hey @andschdk , i thought in your other issue you opened it was tracking for you (at least in foreground). Also let's please try to put everything in one issue as it seems to be related to the same thing

**Comment by yarneo** [comment]
If it's not tracking for you then can you please give me some more info onto when NotificationManager is initialized and does that manager implement `userNotificationCenter:willPresentNotification:withCompletionHandler:`?

**Comment by andschdk** [comment]
Hi @yarneo 
Sorry for opening one more issue, I just think this is not related to each other. This is most likely a bug (or a setup issue on my end), while the other (#119) is a discussion about when and where to track push opens when using the new .

The order of initialisation is:
1. `NotificationManager` (setting `UNUserNotificationCenter.current().delegate = self`)
2. `Mixpanel.initialize(...)`

With the debugger attached it looks like there is no trouble resolving `UNUserNotificationCenter.current().delegate` as I can step to https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/AutomaticEvents.swift#L171

Is it on purpose that the `aClass` var is always pointing to the main application delegate?
https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/AutomaticEvents.swift#L168
Then it is always parsed as argument to the swizzler right? https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/AutomaticEvents.swift#L199

Have you tried it out yourself or am I on my own here 😕 ?

**Comment by yarneo** [comment]
hey @andschdk the latest push to master should be able to resolve your issue, ill try to send out a release by end of week!

**Comment by andschdk** [comment]
Hi @yarneo , thanks for your latest commit.
I am still not able to use another class as `UNUserNotificationCenterDelegate` except for the main application.

It still fails with the swizzling here: https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/Swizzle.swift#L81

I made some updates in the demo project to illustrate the problem. On branch `swizzle-bug-fix-ios10`
https://github.com/andschdk/mixpanel-swift/tree/swizzle-bug-fix-ios10
