### ISSUE TITLE
Swift 4 branch out-of-date

### ISSUE THREAD

**Issue by iwasrobbed** [mixpanel/mixpanel-swift#127]
Any chance we can get `swift4` branch sync'ed up with latest `master`?

**Comment by iwasrobbed** [comment]
Ah, just saw `swift4` branch in the readme, but it seems quite far behind `master`.

**Comment by yarneo** [comment]
definitely, will get that updated in the next day or two.

**Comment by yarneo** [comment]
Hey @iwasrobbed should be good now! let me know if you have any more question. Thanks
