### ISSUE TITLE
Skipped installing mixpanel-swift.framework binary due to the error

### ISSUE THREAD

**Issue by keithbeller** [mixpanel/mixpanel-swift#128]
```
*** Skipped installing mixpanel-swift.framework binary due to the error:
	"Incompatible Swift version - framework was built with swiftlang-802.0.53 clang-802.0.42 and the local version is swiftlang-900.0.63.10 clang-900.0.36."

```

this warning raise when I run carthage update, I could build it by myself use the latest SDK, but it would be better for me download the binary framework directly.

**Comment by yarneo** [comment]
Hey @keithbeller . Unfortunately this is one of the issues with Carthage that when building a binary it can only be used with the current swift you are using. We don't yet have proper releases for Swift4 (swiftlang-900), but once we do you should be able to use the binary framework directly.

What you can do in the meanwhile is this command:
`carthage update --platform iOS --no-use-binaries`
