### ISSUE TITLE
How can I disable mixpanel on development?

### ISSUE THREAD

**Issue by umekun123** [mixpanel/mixpanel-swift#132]
On appDelegate, I used to write like this on obj-c, but in swift, it will crash on development when the app call Mixpanel.mainInstance().track(event: "")

        #if DEBUG
        #else
            Mixpanel.initialize(token: Key.Mixpanel.token)
        #endif

**Comment by Taarna** [comment]
I eneded up using this workaround:

```
struct MixpanelHelper {

    static func setup() {
        #if PRODUCTION
            Mixpanel.initialize(token: Constants.Mixpanel.apiKey)
        #endif
    }

    static func track(event: String, properties: Properties? = nil) {
        #if PRODUCTION
            Mixpanel.mainInstance().track(event: event, properties: properties)
        #endif
    }

    static func time(event: String) {
        #if PRODUCTION
            Mixpanel.mainInstance().time(event: event)
        #endif
    }
}

**Comment by umekun123** [comment]
yeah, that is what I am doing right now too.. It's something I didn't want to do, I wish I could handle it easily like we did on obj-c.

**Comment by yarneo** [comment]
Hey @umekun123, one easier solution would be to set the initialize token to an empty string like so: `Mixpanel.initialize(token: "")` and then the events won't be added to your project. Was this what you were looking for? Thanks

**Comment by umekun123** [comment]
There you go!  It works like a charm, thank you!!
