### ISSUE TITLE
swift 4 branch merge with master

### ISSUE THREAD

**Issue by jethmalani** [mixpanel/mixpanel-swift#138]
When do you plan on merging the swift 4 branch with master?

**Comment by barrault01** [comment]
👍

**Comment by dennislysenko** [comment]
Which swift 4 branch should we be using? swift4 vs swift4updates

**Comment by wgins** [comment]
@dennislysenko Per the [README](https://github.com/mixpanel/mixpanel-swift/blob/master/README.md) you should use the `swift4` branch.

**Comment by yusuftor** [comment]
This needs to be merged asap.

**Comment by yarneo** [comment]
At this time we have no intention in making the master branch swift4. In terms of Swift compatibility, you can use Swift 3.2 with Swift 4 and vice versa, as seen here: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Compatibility.html

Are you currently experiencing problems with integrating this framework with your swift 4 project? If so, could you elaborate more on what you are seeing?

**Comment by jlaws** [comment]
Mixing Swift 3.2 pods and Swift 4 pods is not clean.  It would not be as bad if all libraries were still stuck on 3.2, but most have made the transition to Swift 4.  Is there a reason why you are keeping the legacy 3.2 as the primary branch?  If anything you should have Swift 4 be on master and have a legacy branch for 3.2 like you do for Swift 2.

**Comment by yusuftor** [comment]
What @jlaws said. Mixpanel is the only framework I use (out of 13 other major frameworks) that hasn't transitioned to swift 4 on the master branch.

**Comment by jethmalani** [comment]
I also agree with @jlaws. It makes much more sense to keep the most recent version on the master branch. Anybody who want access to the legacy versions can access them on another branch.

**Comment by piemonte** [comment]
@jlaws ++

**Comment by pchien** [comment]
Hey all. Our plan is to have master be on swift 4 on the next release (date tbd) and have a legacy branch for swift 3.2 when that happens.

**Comment by pchien** [comment]
Sorry for the slow turnaround. Swift 4 is now default on 2.3.0.
