### ISSUE TITLE
Can we get an app extension module for this swift version of the api?

### ISSUE THREAD

**Issue by wvdk** [mixpanel/mixpanel-swift#148]
Like the Mixpanel/AppExtension of the https://github.com/mixpanel/mixpanel-iphone repo

**Comment by yarneo** [comment]
Hi @wvdk , the main Mixpanel module supports App Extensions as well, and therefore there isn't a need for a separate AppExtension module like in the Objective-C repo. Let me know if you have any more questions!

**Comment by wvdk** [comment]
Perfect, thanks. :D Perhaps it'd be good to make a section about that in your documentation page.
