### ISSUE TITLE
Data Race issue

### ISSUE THREAD

**Issue by farhad-ris** [mixpanel/mixpanel-swift#151]
I'm getting lots of data race in this SDK

Data race in Mixpanel.WebSocket.(inputStream in _15C44DA03D3982176B17336E3113081C).setter : Swift.Optional<__ObjC.InputStream> at 0x7b540006db00

are you guys have any plan to address it..?

**Comment by zihejia** [comment]
Hi @farhad-ris, sorry about the late response. Since WebSocket is only used internally without impacting end users. We haven't got any similar issues recently so close it for now. We are happy for you to reopen it if the problem still exists in the latest version.
