### ISSUE TITLE
Snapshotting of app was not working, looks like the Mixpanle code is choosing the wrong window

### ISSUE THREAD

**Issue by NickTrienens** [mixpanel/mixpanel-swift#156]
I was getting a console error message 
[Snapshotting] Drawing a view (0x7fbdacd0e3e0, UIWindow) that has not been rendered at least once requires afterScreenUpdates:YES.

in class ApplicationStateSerializer

func getScreenshotForWindow(at index: Int) -> UIImage? {
        var image: UIImage? = nil

        if let window = **application.keyWindow**, !window.frame.equalTo(CGRect.zero) {
            UIGraphicsBeginImageContextWithOptions(window.bounds.size, true, window.screen.scale)
            if !window.drawHierarchy(in: window.bounds, afterScreenUpdates: **true**) {
                Logger.error(message: "Unable to get a screenshot for window at index \(index)")
            }
            image = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
        }
        return image
    }

fixed window selection, maybe not the best,  but window choice was the issue of the black screen on the mix panel webpage

**Comment by pchien** [comment]
Interesting. @NickTrienens do you have a UIWindow that you've never drawn and aren't using? https://developer.apple.com/documentation/uikit/uiapplication/1623104-windows makes it seem like it would be created by you, not by the system.

**Comment by zihejia** [comment]
hi @NickTrienens, we will close this issue for now, happy for you to reopen it if the problem still exists.
