### ISSUE TITLE
Aliased distinctId from MixpanelInstance.distinctId 

### ISSUE THREAD

**Issue by Hanspagh** [mixpanel/mixpanel-swift#158]
When calling MixpanelInstance.distinctId with an alias user, we get the aliased distinctId and not the distinct seen in our mix panel stats
Ex.
Aliasing a user with createAlias(101, MixpanelInstance.distinctId)
MixpanelInsatance.distinctId returns the same distinctId as seen in the mixpanel stats

If we later identify a user with identify(101)
MixpanelInsatance.distinctId will now return 101

Expected Behavior:
Get the same id as in our mix panel stats

**Comment by pchien** [comment]
Sorry about the slow response @Hanspagh. Unfortunately we can't help you here. If you identify a user to a distinct id that's been aliased, your app is not able to tell what the original distinct id was, or even that it was aliased at all. All the alias mapping is being done on the backend. You can read more [here](https://mixpanel.com/help/questions/articles/how-should-i-handle-my-user-identity-with-the-mixpanel-javascript-library).
