### ISSUE TITLE
Swift 4 Support Please

### ISSUE THREAD

**Issue by wmalloc** [mixpanel/mixpanel-swift#163]
I would like to move my project to use Swift4, swift version of the api does not work with switt 4.

Thanks

**Comment by sheminusminus** [comment]
@wmalloc use this in your podfile:
```
pod 'Mixpanel-swift', :git=> 'https://github.com/mixpanel/mixpanel-swift.git', :branch=> 'swift4'
```

**Comment by pchien** [comment]
Swift 4 is now default for the latest version 2.3.0.
