### ISSUE TITLE
Data race in generic specialisation 

### ISSUE THREAD

**Issue by farhad-ris** [mixpanel/mixpanel-swift#169]
ObjectFilter.swift
```
    func applyReverse(on views: [AnyObject]) -> [AnyObject] {
        var result = [AnyObject]()
        for view in views {
            if doesApply(on: view) {
                **result += getParents(of: view)**
            }
        }
        return result
    }

```

Data race in generic specialization <Swift.AnyObject, Swift.Array<Swift.AnyObject>> of Swift.Array.append<A where A == A1.Element, A1: Swift.Sequence>(contentsOf: A1) -> () at _swiftEmptyArrayStorage

**Comment by AndreyPanov** [comment]
I have the similar problem. Can we fix it somehow?

**Comment by zihejia** [comment]
We will investigate it and get back to you

**Comment by zihejia** [comment]
I'm closing this one for now since no detail information being provided, please feel free to reopen it if anyone still has the same problem.
