### ISSUE TITLE
Swift compile error after mixpanel updated to swift 3.0

### ISSUE THREAD

**Issue by manhcuong27** [mixpanel/mixpanel-swift#17]
Hello,

My project built fine before mixpanel swift 3.0 update. Now I got errors in 2 files: Persistence.swift , and JSONHandle.swift. Please look at the screenshots below, I'm using Xcode 7.3.1

http://img.photobucket.com/albums/v720/taki27/Screen%20Shot%202016-09-17%20at%2010.06.27%20AM.png
http://img.photobucket.com/albums/v720/taki27/Screen%20Shot%202016-09-17%20at%2010.06.16%20AM.png

Thanks.

**Comment by dgoodine** [comment]
Swift 2.x and 3.0 are source code incompatible, so you shouldn't be surprised if code updated for Swift 3.0 doesn't compile in Xcode 7.

**Comment by yarneo** [comment]
Hey @manhcuong27 , based on your report and images, I'm assuming you are still using Swift 2.2. We have now released a new version to support Xcode8 and Swift 2.3. I would strongly recommend to update to Xcode8 as now Xcode7 is outdated.

If you still wish to use Xcode7, then please continue integrating the previous version (v1.0.0)
Cocoapods: pod 'Mixpanel-swift', '1.0.0'
Carthage: github "mixpanel/mixpanel-swift" == 1.0.0
Manual: Goto releases and download release v1.0.0
