### ISSUE TITLE
swift4 and ios 10

### ISSUE THREAD

**Issue by dimohamdy** [mixpanel/mixpanel-swift#173]
<img width="275" alt="screen shot 2018-01-11 at 6 04 02 pm" src="https://user-images.githubusercontent.com/1476754/34834153-ea5d1816-f6f9-11e7-9901-d836ff369d15.png">

```
[NSAttributedString.DocumentAttributeKey.documentType:
                                                    NSAttributedString.DocumentType.html]
```
 is in iOS 11 and in podspec support iOS 8
check docmentation
https://developer.apple.com/documentation/uikit/nsattributedstring.documentreadingoptionkey

**Comment by spsneo** [comment]
I have changed to Swift 4. I am still getting this issue.

**Comment by zihejia** [comment]
hi @spsneo, have you done a clean build?

**Comment by spsneo** [comment]
@zihejia I have done a clean build. Cmd+Shift+K -> Cmd + B

**Comment by Mathengel** [comment]
I am experiencing this same issue after updating to xcode10 and updating the Mixpanel pod to -v 2.4.3

**Comment by cornelbalaban** [comment]
I have the same issue with the Swift library. I did't convert the code to Swift 4 BUT I have XCode Version 10.0 (10A255).

**Comment by kakubei** [comment]
Same issue here, clean build, deleting all caches, updating Mixpanel pod, etc. Nothing seems to work 😢

**Comment by zihejia** [comment]
Xcode 10 comes with swift 4.2 by default, so please use v2.5.0 instead which has a full swift 4.2 support. Otherwise if use v2.4.5 or earlier, please set swift to 4.0 and it should work. Let me know if any issues.

**Comment by kakubei** [comment]
I've changed the project swift version to 4 and still have issues with it. 
I was able to solve it by selecting the Mixpanel-swift pod under the Pods project and changing that Pod specifically to Swift 4.0. I assumed that by changing the whole project to Swift 4.0, the pods would change accordingly, apparently this is not so.
