### ISSUE TITLE
Important: Release Versioning and Swift Version Compatibility

### ISSUE THREAD

**Issue by dgoodine** [mixpanel/mixpanel-swift#18]
The recent release of "v1.0.1" should removed and be named "1.1.0" since Swift 2.2 (in Xcode 7.3.1) and Swift 2.3 (in Xcode 8) are not binary compatible.  Anyone using Carthage is in for a big surprise the next time they do an update and find that their project will no longer build, since the current versioning implies the two versions are compatible.

Furthermore, Carthage can't parse the version correctly if specified with the "v" in the Cartfile, so anyone using Carthage will be dead in their tracks until this is resolved.  (Release versions should only be numeric anyway as a matter of good practice.)

In the future whoever is dropping releases should keep in mind Swift versions (even point releases) will always be binary incompatible, until Swift 4, and possibly even after 4.0.

**Edit**: I just discovered that Carthage is smart about removing the "v", so the following spec in the Cartfile will solve this issue:

`github "mixpanel/mixpanel-swift" == 1.0.0`

**Comment by yarneo** [comment]
Thanks for the heads up @dgoodine.
You are right about the versioning. I'll see what I can do to update the version to be 1.1.0 either today or tomorrow.

**Comment by yarneo** [comment]
After looking into this further, it would be a big impact on our users who integrated through Cocoapods to change a release version. What I suggest right now is that for the users who have *yet* to update their Xcode to version 8, they will have to explicitly define the version like you wrote above. `github "mixpanel/mixpanel-swift" == 1.0.0`

When we eventually decide to have our releases in Swift3, we promise to follow better versioning guidelines.

**Comment by dgoodine** [comment]
That makes sense. Thanks for looking into it. 

-d
