### ISSUE TITLE
String interpolation Alias not being set correctly in Mixpanel

### ISSUE THREAD

**Issue by wfgilman** [mixpanel/mixpanel-swift#180]
I'm having some trouble getting a string interpolation alias to be set properly using the Mixpanel Swift SDK.

When a user signs up, I parse his user id from the API JSON response and concatenate it with "User:" to create an alias. However, despite the user id being a valid, non-zero integer, alias is being registered in Mixpanel as "User:0". I'm only observing this in my deployment builds. Running in debug mode in the Xcode simulator renders registers the alias properly in Mixpanel.
```
let userId = json["user_id"] as! Int
let mixpanel = Mixpanel.mainInstance()
let alias: String = "User:\(userId)"
mixpanel.createAlias(alias, distinctId: mixpanel.distinctId)
```
Casting the alias explicitly as a string doesn't seem to help. I can't figure this one out.

**Comment by zihejia** [comment]
Hi @wfgilman, If running in Xcode simulator works, it might be worth to double check the parsing logic of your user id or the JSON response. If you find an issue with Mixpanel, you are welcome to reopen it.
