### ISSUE TITLE
Invalid parameter not satisfying: bundleProxy != nil in AutomaticEvents.swift line 171

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#183]
Perhaps commit 89eff3a fixed this? 

I'm getting rare crash reports that look like this:

https://imgur.com/a/GfYQv

Seems to happen right at app initialization

**Comment by zihejia** [comment]
Hi @RamblinWreck77, can you confirm if the latest SDK version fixed this?

**Comment by zihejia** [comment]
Looks like there are several issues are similar and related.
https://github.com/mixpanel/mixpanel-swift/issues/201
https://github.com/mixpanel/mixpanel-swift/issues/183
https://github.com/mixpanel/mixpanel-swift/issues/182
So, we will close this one and use https://github.com/mixpanel/mixpanel-swift/issues/201 to discuss and track
