### ISSUE TITLE
Crash on`MixpanelInstance.checkDecide` v2.3.1

### ISSUE THREAD

**Issue by robertofrontado** [mixpanel/mixpanel-swift#184]
Hello, I'm using `Mixpanel-swift v2.3.1` and I just got this crash:

<img width="1182" alt="screen shot 2018-02-20 at 2 01 03 pm" src="https://user-images.githubusercontent.com/11177510/36425400-f5d383da-1646-11e8-918a-732b0489f792.png">

Is this a known issue?

**Comment by zihejia** [comment]
hi @robertofrontado, could you give us more details about this crash? Such as Is it reproducible, more logs, etc.

**Comment by zihejia** [comment]
Hi @robertofrontado , we don't have any other similar report about this crash. I'm closing this one for now, please re-open if you're still experiencing the problem and providing us with more information, like Xcode version, swift version, Mixpanel-swift version, how often it is happening, etc.  Thanks!
