### ISSUE TITLE
Super properties are not sent with the common "First App Open" event

### ISSUE THREAD

**Issue by per2plex** [mixpanel/mixpanel-swift#189]
I'm registering super properties right after initializing the instance, but they don't get sent for the `First App Open` event. All other common mobile events will include the super properties.

Would be nice if there was an option to set super properties within the `initialize` or if the internal `First App Open` event gets deferred. 

```swift
let mixpanelInstance = Mixpanel.initialize(token: token, launchOptions: launchOptions)

mixpanelInstance.registerSuperProperties([
  "App Name": "Test",
  "App Identifier": "com.test.app"
])
```

**Comment by zihejia** [comment]
For now, it doesn't seem to be a high priority, but we might work on it if we have time in future.

**Comment by zihejia** [comment]
We will use another issue to track this, so close this one now.
https://github.com/mixpanel/mixpanel-swift/issues/222

**Comment by zihejia** [comment]
Hi @per2plex , please check our new release v2.5.7 which has a fix for it. Thanks!
https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.5.7
