### ISSUE TITLE
MIXPANEL PROPERTIES 

### ISSUE THREAD

**Issue by veer-suthar** [mixpanel/mixpanel-swift#191]
I run the app, I changed SIM, I triggered another event, but it doesn't change the MixPanel Property.
Issue is that, its not registering properties, when app opens, but if user changes, say cellular network, its not updating.

In this case, wrong data is showing to Customer, which is believing network was A, while user changed network after running/initialization of App.

**Comment by veer-suthar** [comment]
I run the app, I changed SIM, I triggered another event, but it doesn't change the MixPanel Property. 
Issue is that, its not registering properties, when app opens, but if user changes, say cellular network, its not updating. 

In this case, wrong data is showing to Customer, which is believing network was A, while user changed network after running/initialization of App.

**Comment by zihejia** [comment]
hi @veer-suthar , we have fixed the issue in 2.4.2, please try again. Feel free to reopen it if the problem still exists.

**Comment by veer-suthar** [comment]
@zihejia Thanks for fixing it. Your work appreciated. I will update library. Thanks.
