### ISSUE TITLE
Xcode 9.3 build warnings

### ISSUE THREAD

**Issue by phoney** [mixpanel/mixpanel-swift#197]
When building mixpanel-swift 2.4.0 with Xcode 9.3 I get 7 build warnings. Most are in MD5.swift but there are two others that are similar to each other in Connectintegrations.swift and MixpanelInstance.swift.

<img width="463" alt="screen shot 2018-04-23 at 10 52 01 am" src="https://user-images.githubusercontent.com/3106038/39134402-89c806ec-46e4-11e8-8336-77ed5c1b3e21.png">

**Comment by namrata-b** [comment]
I have the same issue.

**Comment by kelvinlauKL** [comment]
I also have the same issue. 👋 @namrata-b

**Comment by zihejia** [comment]
Thanks for reporting, we will fix this.

**Comment by zihejia** [comment]
We have a new release 2.4.1 with a fix to this, so close this for now.
