### ISSUE TITLE
MixPanel files are in the wrong place on iOS

### ISSUE THREAD

**Issue by phoney** [mixpanel/mixpanel-swift#198]
MixPanel puts about five files at the top level of /Library on iOS. That's really not the right place for them. They should go either in Application Support or Caches if they can be reconstituted and they should be inside a folder with MixPanel as part of the name. I would recommend something like
/Application Support/mixpanel/
I see the code that generates the file paths in Persistence.filePathFor()

**Comment by zihejia** [comment]
The files are not in the top level of /Library on iOS but rather in a sandbox, the app specific data container directory. i.e. “/var/mobile/Containers/Data/Application/CFE0B905-3598-47D3-9671-4A9A9E9CE6DF/Library/” and we don't want to store files in Caches cause they are not cache and ios system can clear data stored there at any time.

**Comment by phoney** [comment]
@zihejia The files are in the wrong place. 
See https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

Apple says

 "Put app-created support files in the Library/Application support/ directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. "

"This (Library/) is the top-level directory for any files that are not user data files. You typically put files in one of several standard subdirectories. iOS apps commonly use the Application Support and Caches subdirectories; however, you can create custom subdirectories."

Mixpanel files should go in /Library/Application Support/mixpanel

**Comment by zihejia** [comment]
hi @phoney, you are right. It is suggested to put files in subdirectories as a better practice, this could be a future improvement but it will involve some migration work for not impacting existing users. Since it's quite minor we will put it into backlog for now. Thanks for raising it anyway.

**Comment by phoney** [comment]
I might make a PR for this. For iOS. I'd make a folder:  /Application Support/mixpanel. New files would go there. Existing files would be moved there.

**Comment by zihejia** [comment]
Thanks @phoney!

**Comment by phoney** [comment]
@zihejia I made a pull request to solve this. 
https://github.com/mixpanel/mixpanel-swift/pull/219
