### ISSUE TITLE
Swift 3 Support?

### ISSUE THREAD

**Issue by bennettl** [mixpanel/mixpanel-swift#20]
Currently I'm using Xcode 8, Swift 3, Cocoapods (version 1.1.0.rc.2) and Mixpanel-swift (1.0.1). In my podfile..

pod 'Mixpanel-swift'

But apparently it's not compatible with Swift 3?

<img width="1280" alt="screen shot 2016-09-20 at 1 57 19 pm" src="https://cloud.githubusercontent.com/assets/1672224/18688666/328a2b1c-7f3a-11e6-80dc-1f03231c9b86.png">

**Comment by yarneo** [comment]
Hey @bennettl, our current cocoapods release supports Swift 2.3. If you want to use Swift 3 please go to our swift3 branch: https://github.com/mixpanel/mixpanel-swift/tree/swift3 and install manually.
We will push out a full swift3 release soon

**Comment by yarneo** [comment]
Also you can try putting this in the podfile instead:
pod 'Mixpanel-swift', :git => 'https://github.com/mixpanel/mixpanel-swift.git', :branch => 'swift3'
