### ISSUE TITLE
Deadlock on calling Mixpanel.initialize() in AutomaticProperties.getCurrentRadio()

### ISSUE THREAD

**Issue by dan-rodrigues** [mixpanel/mixpanel-swift#200]
We occasionally see a deadlock when calling `Mixpanel.initialize()` when [this](https://github.com/mixpanel/mixpanel-swift/blob/v2.3.1/Mixpanel/AutomaticProperties.swift#L23) `CTTelephonyNetworkInfo ` instance is accessed.

* Mixpanel v2.3.1
    * We've checked [changes made to master](https://github.com/mixpanel/mixpanel-swift/compare/v2.3.1...master) since then but couldn't spot anything that could affect this.
* Built with Xcode 9.3 (9E145)
    * Same issue seen with Xcode 9.2
* Mixpanel framework built with optimisations enabled
* `Mixpanel.initialize()` is always called on the main thread
* Observed on both simulator and devices

Main thread callstack screenshot captured by one of our developers (numbered 0 to 13).

![screen shot 2018-04-19 at 2 27 29 pm](https://user-images.githubusercontent.com/8379784/39500783-4f5ff8bc-4dfa-11e8-8b91-b542a089a7cc.png)

**Comment by zihejia** [comment]
hi @dan-rodrigues,  i will have a look.

**Comment by zihejia** [comment]
hi @dan-rodrigues , we have fixed the issue in 2.4.2, please try again. Feel free to reopen it if the problem still exists.
