### ISSUE TITLE
Codeless tracking not working properly

### ISSUE THREAD

**Issue by Fyb3roptik** [mixpanel/mixpanel-swift#203]
We are trying to setup and use Codeless tracking, however it recognizes all of the bottom nav as the same button. It is also sensing hidden elements as trackable when in actuality they are not even on the view!

**Comment by Fyb3roptik** [comment]
Is there a setting in Xcode for each button that I need to set?

**Comment by zihejia** [comment]
Hi @Fyb3roptik , sorry for the late response. If you would like further assistance with how to use codeless tracking, please reach out to support@mixpanel.com. Closing this one out, please re-open if you feel there is something wrong with the SDK itself.
