### ISSUE TITLE
Mixpanel swift is failing to build with error `frame is only available on iOS 12.0 or newer`

### ISSUE THREAD

**Issue by aliaziz** [mixpanel/mixpanel-swift#208]
Am using Swift 4 Xcode 10-beta,

**Comment by tikidunpon** [comment]
@aliaziz Hi, what is the version of the mixpanel-swift you use?  I have got the same issue, but it seems like fixed with this commit that merged on v2.4.1. https://github.com/mixpanel/mixpanel-swift/commit/581a61848b4c21bf7c641d94c1af793601e2bbd1

**Comment by leah** [comment]
I was using Mixpanel v2.3.3 and can confirm that updating to the latest version fixes this issue. @aliaziz
