### ISSUE TITLE
optOutTrackingByDefault not respected on OS X

### ISSUE THREAD

**Issue by axchow** [mixpanel/mixpanel-swift#211]
I noticed that the OS X initializers don't respect `optOutTrackingByDefault` -- not sure if this is intentional or not, but the comments seems to suggest that it should be.

**Comment by zihejia** [comment]
Thanks @axchow, we will provide a fix for this.

**Comment by zihejia** [comment]
v2.4.4 has been released and contains the fix, thanks!
