### ISSUE TITLE
Flushing event queue not sending multiple batches

### ISSUE THREAD

**Issue by erenliving** [mixpanel/mixpanel-swift#213]
It appears the check for remaining events in the shadowQueue copy is preventing multiple batches of events to be flushed when the event queue has more than APIConstants.batchSize events in it, instead it is removing all events from the queue after the first batch is sent successfully. This causes the remaining queued events to be lost.

**Comment by zihejia** [comment]
Thanks @erenliving for raising this issue and providing a fix for this! We will release a new version.

**Comment by zihejia** [comment]
v2.4.4 has been released and contains the fix, once again thanks @erenliving !
