### ISSUE TITLE
Carthage: Skipped installing framework binary

### ISSUE THREAD

**Issue by marbetschar** [mixpanel/mixpanel-swift#217]
```
*** Skipped installing mixpanel-swift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)."
```

**Comment by ShadyGhalab** [comment]
Any updates on this?

**Comment by zihejia** [comment]
Thanks for raising this. We will have a look.

**Comment by xxcombat** [comment]
any solutions?

**Comment by jgarciatt** [comment]
Any updates?

**Comment by zihejia** [comment]
From Carthage official docs: "Carthage will check to make sure that downloaded Swift (and mixed Objective-C/Swift) frameworks were built with the same version of Swift that is in use locally. If there is a version mismatch, Carthage will proceed to build the framework from source. " For some reason, Carthage failed to recognize this as a version mismatch. 

Try with `Carthage update --no-use-binaries` will build from source.  Remember to delete Carthage folder and re run it. 

Please checkout https://github.com/Carthage/Carthage#swift-binary-framework-download-compatibility for more detail.

One pain point of Carthage is that we have to ship the prebuilt framework using our local swift version, normally the Carthage version mismatch will solve most of the cases, if not, please use `--no-use-binaries`. 

Please feel free to reopen it if the solution is not working.
