### ISSUE TITLE
Crash in AutomaticProperties / automaticPropertiesLock worker thread

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#221]
Here's the stack trace.

(main thread)

com.apple.main-thread
0  libsystem_kernel.dylib         0x184a5ac64 read + 8
1  Foundation                     0x185986a68 _NSReadFromFileDescriptorWithProgress + 228
2  Foundation                     0x18598687c _NSReadBytesFromFileWithExtendedAttributes + 672
3  Foundation                     0x185952564 -[NSData(NSData) initWithContentsOfFile:options:maxLength:error:] + 184
4  Foundation                     0x185961eb0 +[NSKeyedUnarchiver unarchiveObjectWithFile:] + 88
5  Mixpanel                       0x1040e1540 static Persistence.unarchiveWithFilePath(String) -> Any? (Persistence.swift:229)
6  Mixpanel                       0x1040e19f0 static Persistence.unarchiveWithType(Persistence.ArchiveType, token : String) -> Any? (Persistence.swift:352)
7  Mixpanel                       0x1040e221c specialized static Persistence.unarchiveEvents(token : String) -> [[String : Any]] + 4329136668
8  Mixpanel                       0x10409fe78 MixpanelInstance.unarchive() -> () (MixpanelInstance.swift:913)
9  Mixpanel                       0x1040b3f88 specialized MixpanelInstance.init(apiToken : String?, launchOptions : [UIApplicationLaunchOptionsKey : Any]?, flushInterval : Double, name : String, automaticPushTracking : Bool, optOutTrackingByDefault : Bool) -> MixpanelInstance (MixpanelInstance.swift:303)
10 Mixpanel                       0x10409b8cc static Mixpanel.initialize(token : String, launchOptions : [UIApplicationLaunchOptionsKey : Any]?, flushInterval : Double, instanceName : String, automaticPushTracking : Bool, optOutTrackingByDefault : Bool) -> MixpanelInstance (Mixpanel.swift:45)

(Crashed Thread: automaticPropertiesLock
EXC_BAD_INSTRUCTION 0x00000000de0a05bd)

Crashed: automaticPropertiesLock
0  Mixpanel                       0x104066dac Any (AutomaticProperties.swift)
1  Mixpanel                       0x10406562c _T08Mixpanel19AutomaticPropertiesC10propertiess10DictionaryVySSypGvpZfiAGycfU_ (AutomaticProperties.swift:29)
2  Mixpanel                       0x1040654b0 globalinit_33_EA3BC46B13D3E888870212C59FEB66EA_func1 (AutomaticProperties.swift:24)
3  libdispatch.dylib              0x1848e4a60 _dispatch_client_callout + 16
4  libdispatch.dylib              0x184917364 dispatch_once_f$VARIANT$armv81 + 60
5  Mixpanel                       0x1040a4ce4 MixpanelInstance.(setCurrentRadio() -> ()).(closure #1).(closure #1) (MixpanelInstance.swift:638)
6  Mixpanel                       0x1040e6378 ReadWriteLock.(read(closure : () -> ()) -> ()).(closure #1) (ReadWriteLock.swift:20)
7  Mixpanel                       0x1040b7154 partial apply for thunk (MixpanelInstance.swift)
8  libswiftDispatch.dylib         0x1049b5598 _hidden#129_ (__hidden#878_:238)
9  libswiftDispatch.dylib         0x1049aeda0 _hidden#38_ (__hidden#878_)
10 libdispatch.dylib              0x1848e4a60 _dispatch_client_callout + 16
11 libdispatch.dylib              0x184921ed4 _dispatch_queue_barrier_sync_invoke_and_complete + 56
12 libswiftDispatch.dylib         0x1049bbca0 _hidden#225_ (__hidden#878_:225)
13 libswiftDispatch.dylib         0x1049b5428 _hidden#128_ (__hidden#878_:244)
14 libswiftDispatch.dylib         0x1049b5c54 DispatchQueue.sync<A> (flags : DispatchWorkItemFlags, execute : () throws -> A) throws -> A (__hidden#1491_:285)
15 Mixpanel                       0x1040a4c6c MixpanelInstance.(setCurrentRadio() -> ()).(closure #1) (MixpanelInstance.swift:23)
16 Mixpanel                       0x10409e704 _T0Ieg_IeyB_TR (MixpanelInstance.swift)
17 libdispatch.dylib              0x1848e4aa0 _dispatch_call_block_and_release + 24
18 libdispatch.dylib              0x1848e4a60 _dispatch_client_callout + 16
19 libdispatch.dylib              0x1849231d4 _dispatch_queue_serial_drain$VARIANT$armv81 + 568
20 libdispatch.dylib              0x184923af8 _dispatch_queue_invoke$VARIANT$armv81 + 328
21 libdispatch.dylib              0x18492449c _dispatch_root_queue_drain_deferred_wlh$VARIANT$armv81 + 332
22 libdispatch.dylib              0x18492c46c _dispatch_workloop_worker_thread$VARIANT$armv81 + 612
23 libsystem_pthread.dylib        0x184c17e70 _pthread_wqthread + 860
24 libsystem_pthread.dylib        0x184c17b08 start_wqthread + 4

**Comment by zihejia** [comment]
hi @RamblinWreck77, sorry for the late response. Did you try the latest version?

**Comment by zihejia** [comment]
Hi @RamblinWreck77, Please try our latest version v2.4.5, it has a fix to unarchive crash, it might fix this issue.
