### ISSUE TITLE
RSV_Init Crash

### ISSUE THREAD

**Issue by bettola** [mixpanel/mixpanel-swift#228]
Integration Method: CocoaPods
Xcode Version: 9.4
Library Version: 2.4.4
Platform: iOS 11
Language: Swift
Description: I have a crash repeating quite frequently in applicationWillResignActive

#16. Crashed: com.tonymillion.nmreachability
0  libsystem_kernel.dylib         0x180ecd2ec __pthread_kill + 8
1  libsystem_pthread.dylib        0x18106e288 pthread_kill$VARIANT$mp + 376
2  libsystem_c.dylib              0x180e3bd0c abort + 140
3  libsystem_malloc.dylib         0x180f05838 szone_size + 634
4  libresolv.9.dylib              0x18c5f0f28 res_9_ndestroy + 56
5  libresolv.9.dylib              0x18c5f28bc res_9_vinit + 116
6  MyApp                       0x10063345c RSV_init + 4378014812
7  MyApp                       0x10060f27c CPM_setValue + 4377866876
8  MyApp                       0x10057fd30 __37-[CFSession setupSessionReachability]_block_invoke + 4377279792
9  MyApp                       0x10059173c -[CFReachability reachabilityChanged:] + 4377351996
10 MyApp                       0x1005911a0 TMReachabilityCallback + 4377350560
11 SystemConfiguration            0x182199644 reachPerformAndUnlock + 540
12 libdispatch.dylib              0x180d38b24 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x180d38ae4 _dispatch_client_callout + 16
14 libdispatch.dylib              0x180d42a38 _dispatch_queue_serial_drain$VARIANT$mp + 608
15 libdispatch.dylib              0x180d43380 _dispatch_queue_invoke$VARIANT$mp + 336
16 libdispatch.dylib              0x180d43d4c _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
17 libdispatch.dylib              0x180d4c11c _dispatch_workloop_worker_thread$VARIANT$mp + 668
18 libsystem_pthread.dylib        0x18106be70 _pthread_wqthread + 860
19 libsystem_pthread.dylib        0x18106bb08 start_wqthread + 4

--

#0. com.apple.main-thread
0  Mixpanel                       0x1014d92b0 fixStringForCoreData(objc_object*) + 4208
1  Mixpanel                       0x1014314f8 @objc MixpanelInstance.applicationWillResignActive(Notification) -> () + 44
2  CoreFoundation                 0x1813d8c3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
3  CoreFoundation                 0x1813d81b8 _CFXRegistrationPost + 428
4  CoreFoundation                 0x1813d7f14 ___CFXNotificationPost_block_invoke + 216
5  CoreFoundation                 0x18145584c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
6  CoreFoundation                 0x18130ef38 _CFXNotificationPost + 384
7  Foundation                     0x181d7fbbc -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
8  UIKit                          0x18b3d054c -[UIApplication _sendWillEnterForegroundCallbacks] + 232
9  UIKit                          0x18afe1e10 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1388
10 UIKit                          0x18bc7772c __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 296
11 UIKit                          0x18afe1268 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
12 UIKit                          0x18ba5c9b8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
13 UIKit                          0x18bbaaae8 _performActionsWithDelayForTransitionContext + 112
14 UIKit                          0x18afe0c88 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
15 UIKit                          0x18afe0624 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
16 UIKit                          0x18b01e3b0 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468
17 FrontBoardServices             0x183c44f24 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212
18 libdispatch.dylib              0x180d38ae4 _dispatch_client_callout + 16
19 libdispatch.dylib              0x180d401f4 _dispatch_block_invoke_direct$VARIANT$mp + 224
20 FrontBoardServices             0x183c78878 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
21 FrontBoardServices             0x183c7851c -[FBSSerialQueue _performNext] + 404
22 FrontBoardServices             0x183c78ab8 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
23 CoreFoundation                 0x1813ef404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
24 CoreFoundation                 0x1813eec2c __CFRunLoopDoSources0 + 276
25 CoreFoundation                 0x1813ec79c __CFRunLoopRun + 1204
26 CoreFoundation                 0x18130cda8 CFRunLoopRunSpecific + 552
27 GraphicsServices               0x1832ef020 GSEventRunModal + 100
28 UIKit                          0x18b2ed78c UIApplicationMain + 236
29 MyApp                       0x1000ba124 main (AppDelegate.swift:17)
30 libdyld.dylib                  0x180d9dfc0 start + 4

**Comment by zihejia** [comment]
hi @bettola, thanks for raising this, we will have a look.
