### ISSUE TITLE
MIXPANEL_NO_IFA support for Swift library

### ISSUE THREAD

**Issue by jarosan** [mixpanel/mixpanel-swift#231]
Hello,

I want to migrate from Obj-C library to Swift, but couldn't find any information if `mixpanel-swift` supports the `MIXPANEL_NO_IFA` setting like in obj-c counterpart. Is there an alternative way to set this configuration?

Thanks in advance.

**Comment by zihejia** [comment]
Hi @jarosan , we have released 2.5.0 which enable you to set `MIXPANEL_NO_IFA` in `Active Compilation Conditions` in build settings. Thanks for raising this issue.
