### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found:

### ISSUE THREAD

**Issue by DariDev** [mixpanel/mixpanel-swift#233]
I keep getting this issue whenever I try to run my app after updating Mixpanel using Cocoapods to version 2.4.5, the previous version that I had was 2.3.1 I think

**dyld: lazy symbol binding failed: Symbol not found: _$S8MixpanelAAC10initialize5token13launchOptions13flushInterval12instanceName21automaticPushTracking06optOutL9ByDefaultAA0A8InstanceCSS_SDySo019UIApplicationLaunchE3KeyaypGSgSdSSS2btFZ
  Referenced from: /Users/ahmaddari/Library/Developer/CoreSimulator/Devices/24A420B3-02C6-4E40-B4AA-D18AD32236BF/data/Containers/Bundle/Application/AE4F8614-C9BE-416F-B041-38991DA50D02/DragDrop.app/Frameworks/LuckyTripSDK.framework/LuckyTripSDK
  Expected in: /Users/ahmaddari/Library/Developer/CoreSimulator/Devices/24A420B3-02C6-4E40-B4AA-D18AD32236BF/data/Containers/Bundle/Application/AE4F8614-C9BE-416F-B041-38991DA50D02/DragDrop.app/Frameworks/Mixpanel.framework/Mixpanel**

I don't get it, what am I expected to do exactly ?
I'm currently on Xcode 10 beta 6 trying to make my app run on iOS 12 simulator

**Comment by zihejia** [comment]
hi @DariDev, you may clean your build folder and delete the app from simulator and try again, looks like it's linking to the old version.
