### ISSUE TITLE
MixpanelDemo MD5 compilation fails

### ISSUE THREAD

**Issue by rubensantiago** [mixpanel/mixpanel-swift#235]
I'm trying to run the MixpanelDemo app but receive the following compilation error in `MD5.swift`

`Binary operator '-' cannot be applied to operands of type 'D.IndexDistance' and 'Int'`

On line 354

**Comment by zihejia** [comment]
Hi @rubensantiago , we've fixed this issue since v2.4.1, which version are you using now?

**Comment by rnh8wb** [comment]
I'm getting this error with 2.4.5. Also getting an error "Missing argument for parameter 'capacity' in call" in MD5.swift

**Comment by zihejia** [comment]
in 2.4.5, 'D.IndexDistance' has already been replaced with 'Int', so it's no longer there. Have you ever tried with cleaning your build directory and compile again? Also which line compains about the error "Missing argument for parameter 'capacity' in call"?

**Comment by angelakoceva** [comment]
@zihejia I have the same problem. 
Line 317 and 342.

**Comment by rnh8wb** [comment]
I'm getting "Missing argument for parameter 'capacity' in call" on line 317 ( valuePointer.deallocate() ) and "Binary operator '-' cannot be applied to operands of type 'D.IndexDistance' and 'Int' on line 342 ( let end = Swift.min(self.chunkSize, self.data.count - offset) ).

Xcode 9.2
Swift 4.0
Deployment Target 11.0
Mixpanel-swift 2.4.5

**Comment by zihejia** [comment]
2.4.5 is built with swift 4.1. We fixed the deprecated syntax and made it compatible with swift 4.1. If you need to stick to 4.0, you can use mixpanel-swift 2.4.0 or upgrade to Xcode 10, it has a swift 4.0 embedded.
