### ISSUE TITLE
Remove SwiftLint warning from project file

### ISSUE THREAD

**Issue by krbarnes** [mixpanel/mixpanel-swift#24]
Please stop warning users about SwiftLint installation. 

[mixpanel-patch.txt](https://github.com/mixpanel/mixpanel-swift/files/506610/mixpanel-patch.txt)

**Comment by yarneo** [comment]
Thanks @krbarnes , I'll send that fix out soon

**Comment by yarneo** [comment]
This has been pushed to master, thanks for your help!

**Comment by krbarnes** [comment]
If you guys would just alias swiftlint to mixpanel-swiftlint, you could run it yourselves without forcing users of your library to see all of the mixpanel swiftlint errors.

ie change your project file to run:
```
if which mixpanel-swiftlint >/dev/null; then
mixpanel-swiftlint
fi
```
