### ISSUE TITLE
Xcode 10  - Frame is only avaiable on iOS 12.0 or newer.

### ISSUE THREAD

**Issue by mohdsafadsaal** [mixpanel/mixpanel-swift#240]
Hi ,

We are currently using Xcode 10 and facing issue with Mixpanel-swift Pod. Did any one fix this issue with backward compatiblity?

**Comment by zihejia** [comment]
hi @mohdsafadsaal , which mixpanel-swift version are you using? We are currently working on Xcode 10 support, the deployment target will still be iOS 8 and above.

**Comment by aberguno** [comment]
i have the same error with swift 3 and Mixpanel-swift 2.2.3

**Comment by zihejia** [comment]
hi @aberguno , what is the error?

**Comment by mohdsafadsaal** [comment]
> hi @mohdsafadsaal , which mixpanel-swift version are you using? We are currently working on Xcode 10 support, the deployment target will still be iOS 8 and above.

we use Mixpanel-swift (2.4.5).

**Comment by zihejia** [comment]
hi @mohdsafadsaal , could you give me a screenshot of the error? thanks!

**Comment by zihejia** [comment]
hi @aberguno , this is probably a swift bug, the error(only available on iOS 12) does not seem to be relevant. Previously we have the same compile error on iPhone 5 and we have fixed this issue in 2.4.1. If you need to stick to 2.2.3, the workaround is to change line 97 with `return ($0 as! UITableViewCell).frame.origin.y < ($1 as! UITableViewCell).frame.origin.y`

**Comment by aberguno** [comment]
thanks @zihejia that fixed the problem, are you going to update the pod build compatible with swift 3 to work on xcode 10?

**Comment by sakkaras** [comment]
I am experiencing the same issue with the latest version. It will be fixed?

**Comment by zihejia** [comment]
hi @sakkaras , not sure which swift version you are using, I will appreciate it if you could paste the error log. The current version 2.4.5 doesn't support Xcode 10 with swift 4.2, we will soon release a new version fully Xcode 10 and swift 4.2.

**Comment by zihejia** [comment]
hi @aberguno , we don't have plan to support old version with Xcode 10 just yet but we can provide patch fix if needed.

**Comment by sakkaras** [comment]
Thanks for the quick response @zihejia. I am using Swift 4.0 and Mixpanel 2.4.4. Error log is the same as the picture @aberguno posted previously.

**Comment by zihejia** [comment]
hi @sakkaras , no worries. I'm closing this one for now.
