### ISSUE TITLE
Failed while building the project

### ISSUE THREAD

**Issue by MaxOstPM** [mixpanel/mixpanel-swift#242]
<img width="380" alt="screen shot 2018-09-21 at 22 33 57" src="https://user-images.githubusercontent.com/19346197/45902411-03991e80-bdef-11e8-8a44-2bc0dbba858a.png">

**Comment by zihejia** [comment]
Hi @MaxOstPM , which Mixpanel version are you using? For swift 4.2, you need to upgrade Mixpanel-swift to 2.5.0. If you need to stick to Mixpanel 2.4.5 or earlier, you can set Swift to 4.0 on `Mixpanel-swift` target.

**Comment by MaxOstPM** [comment]
Hi @zihejia , already using 2.5.0 version :(

**Comment by zihejia** [comment]
hi @MaxOstPM , how do you integrate Mixpanel, by cocoapods, carthage or manual? If you upgrade Mixpanel from the previously version, you need to clean the build folder first and compile again.

**Comment by MaxOstPM** [comment]
@zihejia via cocoapods

**Comment by zihejia** [comment]
Hi @MaxOstPM , it looks like your swift is not set to 4.2.  Could you double check what is the swift version in Mixpanel-swift target under Pods project? for 2.5.0, you need to set to swift 4.2.

**Comment by MaxOstPM** [comment]
@zihejia everything is working now. It was my fault(
Thnx!

**Comment by zihejia** [comment]
no worries, good to know it works!
