### ISSUE TITLE
Errors compiling with XCode 10 (v2.5.0)

### ISSUE THREAD

**Issue by Pedroalexandrelopes** [mixpanel/mixpanel-swift#243]
After updating Mixpanel-swift to 2.5.0, I'm still getting errors.
Here's an example. I'm I missing something? Also tried to change swift version from 3 to 4.2.

<img width="1265" alt="screen shot 2018-09-24 at 11 36 31" src="https://user-images.githubusercontent.com/130867/45948188-dfa42b80-bfee-11e8-8a33-8d378dee01d1.png">

**Comment by zihejia** [comment]
Hi @Pedroalexandrelopes , you need to set swift version to 4.2 for Mixpanel target, not just your main target.

**Comment by zihejia** [comment]
Hi @Pedroalexandrelopes , I'm closing this one out, please re-open if you're still experiencing the problem and the solutions suggested don't resolve it.
