### ISSUE TITLE
Can't use 2.2.3 anymore

### ISSUE THREAD

**Issue by Bjornftw** [mixpanel/mixpanel-swift#247]
I'm using version `2.2.3` in my app, but I can't run my app anymore in xCode 10.

![image](https://user-images.githubusercontent.com/2643275/46159175-ed241480-c27f-11e8-9131-672edd80b72d.png)

**Comment by zihejia** [comment]
Hi @Bjornftw, we are no longer support 2.2.3 for Xcode 10, please upgrade to 2.5.0 for Xcode 10. In case you need to stick to 2.2.3, please replace the error line with below:
`return ($0 as! UITableViewCell).frame.origin.y < ($1 as! UITableViewCell).frame.origin.y`
