### ISSUE TITLE
 "swift_version" needs to be specified in podspec

### ISSUE THREAD

**Issue by ProiOSDeveloper** [mixpanel/mixpanel-swift#249]
"swift_version": "4.2" needs to be specified for mixpanel-swift in podspec version 2.5.0.
Issue: The project with swift version 4.0 and using mixpanel-swift version 2.5.0, the mixpanel-swift still compiles with swift version 4.0 producing multiple compile time errors.

**Comment by rodolfohelfenstein** [comment]
Same problem here =(

**Comment by zihejia** [comment]
It looks like what CocoaPods does when you run pod install is that it uses the value of SWIFT_VERSION you have set on your own app project and set the same SWIFT_VERSION value for the Pods.xcodeproj targets. Starting from CocoaPods 1.4.0, it allows to set s.swift_version, we will add it the podspec in our next version. Thanks for raising this!

**Comment by zihejia** [comment]
Hi @ProiOSDeveloper @rodolfohelfenstein , thanks for raising this. We have released 2.5.1 and has the fix. Please note: CocoaPods 1.4.0 and above is required. I'm closing this one now.
