### ISSUE TITLE
Remove usage of private class/selector

### ISSUE THREAD

**Issue by g-Off** [mixpanel/mixpanel-swift#25]
https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/UIViewSelectors.swift#L88
This is a dangerous thing to do as a 3rd party framework and risks users of Mixpanel's framework from having their apps rejected from the app store.

**Comment by yarneo** [comment]
Thanks @g-Off , we have never had issues with this in the past with our Objective-C SDK. If you do find Apple rejecting over this, please reach out and we can revisit this. Thanks.
