### ISSUE TITLE
Error: 'frame' is only available on iOS 12 or newer in XCode 10

### ISSUE THREAD

**Issue by fatinWasta** [mixpanel/mixpanel-swift#257]
Hello,
My project was built in swift 3, but as now I m trying to shift my project into swift 4, somehow I'm getting error `'frame' is only available on iOS 12 or newer` from `objectFilter.swift` file. Adding screenshot for reference. Looking forward for your reply. :)

<img width="396" alt="screenshot 2018-10-11 at 11 25 47 pm" src="https://user-images.githubusercontent.com/14032221/46823892-0b742f00-cdad-11e8-9d66-618a8288af45.png">

**Comment by zihejia** [comment]
Hi @fatinWasta , please upgrade to 2.5.1 which fully supports Xcode 10 and swift 4.2. If you need to stick to the old version, here is a workaround: 
In ObjectFilter.swift, change the complaining line into 
`return ($0 as! UITableViewCell).frame.origin.y < ($1 as! UITableViewCell).frame.origin.y`

**Comment by zihejia** [comment]
I'm closing this one now, can use https://github.com/mixpanel/mixpanel-swift/issues/240 for additional reference
