### ISSUE TITLE
App extension target

### ISSUE THREAD

**Issue by JamieWhite** [mixpanel/mixpanel-swift#26]
Have just spotted you have a Swift project now so thought I'd check it out.

The project wont link with an app extension because the "App extension API only" build setting isn't set. In your ObjC project you have a separate target for this - I'm not sure why but I'm sure you have your reasons. It would be good to sort this in the Swift project.

I'm using Carthage to build.

**Comment by yarneo** [comment]
Hi @JamieWhite, the Swift SDK doesn't support App Extensions at this time. Feel free to use the Objective-C SDK in the meanwhile as it provides that capability.

**Comment by JamieWhite** [comment]
That's the plan.

**Comment by JackieQi** [comment]
👍

**Comment by andrewwilliams** [comment]
+1 for App extension support - would love to use this in my iMessage app.

**Comment by obuseme** [comment]
👍 I need this too

**Comment by yarneo** [comment]
We now support App Extensions! See https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.1.4

Thanks!
