### ISSUE TITLE
Mixpanel in the iOS today widget extension

### ISSUE THREAD

**Issue by arctouch-pedrocosta** [mixpanel/mixpanel-swift#268]
How is the right way to support Mixpanel in the iOS today widget extension? I used the latest version of the Mixpanel SDK and it seems that the events are not being triggered for the extension but are normally being triggered for the main app.

I have two targets set in my Podfile. One for the main app and one of the extension and both of them are using ```pod 'Mixpanel-swift'```

**Comment by zihejia** [comment]
Hi @arctouch-pedrocosta , you could turn on logging by calling `Mixpanel.mainInstance().loggingEnabled = true` and see if there is any error. In the meantime, you are welcome to contact support@mixpanel.com for any further help or general usage tips.

**Comment by arctouch-pedrocosta** [comment]
Will reach out to support@mixpanel.com, Thank you.
