### ISSUE TITLE
Crash on 2.5.4

### ISSUE THREAD

**Issue by bettola** [mixpanel/mixpanel-swift#269]
Hi!
I am having a crash on this line in 2.5.4. Everything was good until 2.5.4. Tested on iPhone X simulator iOS 12.1

`Mixpanel.mainInstance().people.set(property: "IDFA", to: "xyz")`

**Comment by zihejia** [comment]
hi @bettola , have you ever called `initialize(token:)` before this call `Mixpanel.mainInstance().people.set(property: "IDFA", to: "xyz")`? In Mixpanel SDK, calling initialize is a prerequisite before making any `Mixpanel.mainInstance()` reference and it will throw a fatalError if not doing so.  If that is not your case, could you share your code snippet and the crash log to help us diagnose the issue better? Thanks!

**Comment by bettola** [comment]
Thanks @zihejia . That is now sorted!
