### ISSUE TITLE
Conditionally conform Array and Dictionary to MixpanelType based on Element type

### ISSUE THREAD

**Issue by nevil** [mixpanel/mixpanel-swift#271]
Array (and Dictionary) are both extended to conform to MixpanelType.
The elements might not conform so the isValidNestedType function seems to be used to assert that all elements does conform to MixpanelType.

What about using the conditional conformance feature of Swift to change the code to:
```swift
extension Array: MixpanelType where Element: MixpanelType {
}
```

I believe this means all isValidNestedType functions can also be removed.

**Comment by zihejia** [comment]
hi @nevil , thanks for the suggestion. `where` is a nice feature but how to validate if the user defined properties is MixpanelType? It only limits the access to the methods inside the `where` protocol. Maybe I misunderstood, you are more than welcome to open a PR.

**Comment by zihejia** [comment]
I'm closing this one for now, you are welcome to open a PR anytime for any issue to improve Mixpanel SDK.
