### ISSUE TITLE
Exception when archiving to file

### ISSUE THREAD

**Issue by drfindley** [mixpanel/mixpanel-swift#272]
Our top crasher in our app is when mixpanel crashes trying to archive an event it tracked. See the crashlog below. Not sure how it's nil

[com.bluejeansnet.blue_issue_2503_crash_f91e20b119b946d3bd0d4e5662164591_DNE_0_v2.txt](https://github.com/mixpanel/mixpanel-swift/files/2678127/com.bluejeansnet.blue_issue_2503_crash_f91e20b119b946d3bd0d4e5662164591_DNE_0_v2.txt)

**Comment by zihejia** [comment]
hi @drfindley, which sdk version are you using?

**Comment by drfindley** [comment]
We are using release 2.5.5

Adam

**Comment by phoney** [comment]
This

# RAM Free: < 1%

might cause this to fail

11 Mixpanel                       0x1116b83b9 specialized static Persistence.archiveToFile(_:object:token:) (Persistence.swift:136)

**Comment by drfindley** [comment]
That was a random crash of hundreds we have that I grabbed. Here's another one with 60% free ram

[com.bluejeansnet.blue_issue_2503_crash_14f389956e6f41a8a7b018b2512644ff_DNE_0_v2.txt](https://github.com/mixpanel/mixpanel-swift/files/2756562/com.bluejeansnet.blue_issue_2503_crash_14f389956e6f41a8a7b018b2512644ff_DNE_0_v2.txt)

**Comment by phoney** [comment]
Hmmm. So that looks like this: https://github.com/mixpanel/mixpanel-swift/issues/152

The NSKeyedArchiver methods used in both places are now deprecated (on iOS 12) and probably could be superseded by use of Codable for archiving and unarchiving.

**Comment by drfindley** [comment]
@phoney Yes, I applied the PR to my users locally and it does fix the problem, well it at least catches the problem and prevents a crash. It essentially is #152, but this handles the encoder crash instead of the decoder crash.

Codable should solve this problem as well.

**Comment by zihejia** [comment]
hi @drfindley @phoney, I am really sorry the delay. Thanks so much for the PR and feedback, you are more than welcome to provide PRs or any feedback/suggestion to make our SDK better. Now the PR has been merged and we will release a new version for it.

**Comment by drfindley** [comment]
@zihejia  No worries on the delay. I'll be sure to check this with the next release and then close this. Thanks! Happy to provide a PR.

**Comment by zihejia** [comment]
v2.5.7 has released with the fix in it. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.5.7
Once again, thanks guys. @drfindley @phoney
