### ISSUE TITLE
Why is ExceptionWrapper in OBJ C ?

### ISSUE THREAD

**Issue by gsabran** [mixpanel/mixpanel-swift#278]
Hi,

I'm wondering why the ExceptionWrapper is written in obj C. It makes build with less common tools like BUCK harder.

**Comment by phoney** [comment]
If you look at the code it's only used in one place where it wraps NSKeyedArchiver. Apparently NSKeyedArchiver throws Obj-C exceptions and they can't be caught by swift. Without that wrapper the app will crash if an exception is thrown. 

The use of this Obj-C wrapper is of course a band aid solution. Maybe you should ask why is NSKeyedArchiver used when Codable could be used?

This "solution" was added Aug 2018.

**Comment by gsabran** [comment]
Thanks. Yes that was my guess as well.

**Comment by zihejia** [comment]
Thanks guys, we will consider the Codable option in the near future release, please stay tuned.
