### ISSUE TITLE
Incorrect SDK behavior because of thread switching in most of the functions

### ISSUE THREAD

**Issue by pateljay43** [mixpanel/mixpanel-swift#280]
I have two different scenarios and both of them are cause by same logic: Thread switching

1. When I try to set super property it does not set it for my first event. The reason I assume is my first event is tracked way before those super properties are even completely set in the SDK.

2. I track my events in proper order to make sure I can use User Flows. But sometimes the SDK switches their order because they are tracked way to close to each other (in 1-5 milliseconds).

These both issue are straight because of the thread switching inside the mixpanel library.

Someone has to fix this. Or if someone can provide more details on why exactly do we need to switch threads inside most of the functions.

**Comment by pateljay43** [comment]
Hello -. I am just trying to follow up with anyone and check for any possible solution here.

**Comment by pateljay43** [comment]
For anyone out there here is an article from Mixpanel describing this issue in detail:
https://help.mixpanel.com/hc/en-us/articles/115004499503?input_string=out+of+order

No solution so far. But I suggest to converting that timestamp value from seconds to nanoseconds.

**Comment by zihejia** [comment]
We have fixed this in v3.0.0.beta and we have no plan to fix it in 2.x. Marking it closed now.

You can use Swift Package Manager to install the beta version for now(Follow the prompts using the URL for this repository and point to branch `3.0.0.beta`).

3.0.0.beta is fully supported by us just without Messages & Experiments. On Jan 1, 2022, we’ll remove the [Messages & Experiments](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/#:~:text=A%20year%20from%20now%2C%20on,offering%20discounts%20for%20getting%20started) feature from Mixpanel and formally release 3.0.0.
