### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [mixpanel/mixpanel-swift#294]
## Expected Results

No warning to convert Mixpanel.framework to Swift 5

## Actual Results

Xcode created warnings to convert Mixpanel.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by zihejia** [comment]
hi @jlaws , thanks for bringing this up. I will have a look.

**Comment by zihejia** [comment]
Hi @jlaws We have released 2.6.2 that has swift 5 support.  Thanks!
https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.2

**Comment by jlaws** [comment]
Thanks for the quick turnaround!
