### ISSUE TITLE
Swift 5 update for Carthage

### ISSUE THREAD

**Issue by lemonkey** [mixpanel/mixpanel-swift#295]
While Swift 5 is ABI stable, it doesn't have module stability yet.

Attempting to build under Xcode 10.2's Swift 5 compiler fails due to the Mixpanel module being built under Swift 4.2, etc.

**Comment by zihejia** [comment]
Hi @lemonkey , thanks! We are currently working on it.

**Comment by lemonkey** [comment]
Thanks!

**Comment by zihejia** [comment]
Hi @lemonkey  We have released 2.6.2 that has swift 5 support.  Thanks!
https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.2

**Comment by lemonkey** [comment]
Thanks!
