### ISSUE TITLE
How to configure Mixpanel for not upload IP address by default

### ISSUE THREAD

**Issue by iamqk** [mixpanel/mixpanel-swift#297]
I know through official help page https://help.mixpanel.com/hc/en-us/articles/115004494803-Disable-Geolocation-Collection by changing useIPAddressForGeoLocation default value to fulfill this need. But should this need be some configuration in the future?

**Comment by zihejia** [comment]
hi @iamqk , that's a good suggestion, we will consider supporting configuration during `initialize` in the future release. For now it's actually configurable through `Mixpanel.mainInstance().useIPAddressForGeoLocation = false`, no need to change Mixpanel code.
