### ISSUE TITLE
Avast AV reports mixpanel as MacOS:Bundlore-BV [Adw]

### ISSUE THREAD

**Issue by eldare** [mixpanel/mixpanel-swift#299]
While building via Carthage, avast anti-virus reports mixpanel as MacOS:Bundlore-BV [Adw].

**Comment by zihejia** [comment]
Hi @eldare, which version you have experienced this issue? Could you share a screen shot of Avast anti-virus reports?

**Comment by zihejia** [comment]
i'm closing this one out, will re-open if you're still experiencing the problem
