### ISSUE TITLE
Highly degraded UX with mixpanel

### ISSUE THREAD

**Issue by angelolloqui** [mixpanel/mixpanel-swift#300]
Hi, 

We have been using Mixpanel for a bit more than a year, and for the last few months we have seen a curious bug that degrades hugely the user experience on the app. It happens after going to background in some particular section of the app, and coming back again to foreground without killing it. I was sceptical about it being caused by mixpanel, but I can only reproduce it when Mixpanel is enabled, and even more, I got this trace when profiling:

![Screen Shot 2019-04-24 at 18 50 47](https://user-images.githubusercontent.com/1382659/56677964-ee0c1000-66c1-11e9-93bc-87b5f19cf5c9.png)

As you can see, for some reason, when switching tabs there is a call to a swizzled method inside Mixpanel that is taking up to 6 seconds on the main thread by just switching tabs a couple of times. In particular, the swizzle seems to be started at `UIView.didMoveFromWindow:toWindow:` and goes down in some internal Mixpanel methods to `ObjectSelector.isLeafSelected(leaf:root:finalPredicate:)`, which does basically 2 operations taking half the time each (`ObjectFilter.doesApply(on:)` and `ObjectFilter.applyReverse(on:)`)

My question is, why does this happen? how can I prevent it from happening? Is there any setting in the library or the dashboard that I can turn off to prevent this swizzling or at least the expensive part of it?

By the way, I have read that it could be related to A/B testing, but in my case there is no active A/B experiment (although there are some active Messages action showing up some in app message)

Mixpanel version:
```pod 'Mixpanel-swift', '2.5.7'```

Project's dashboard URL:
https://mixpanel.com/report/1611725

Thanks,

**Comment by angelolloqui** [comment]
OK, I have continued the research and I have found out that the cause was the “Codeless Binding". We had 7 or 8 codeless events in place, and that resulted in the extremly low performance seen. After removing the codeless events, everything is responding normally again.

I think you should add a warning on your Codeless setup advising not to use it too much, or at least, informing of the huge performance degradation caused by it. In our case, the performance issue was much more important than the value added by the events themselves.

**Comment by angelolloqui** [comment]
One thing I can not explain yet is why, in our project, it started to happen only after going to background and foregrund, and not on the first lunch. It might be related to how Mixpanel manages caching or activates this feature, but I do not have enough details to give a proper response. Maybe you can throw some light to it.

**Comment by pmurphyjam** [comment]
So we're seeing something similar in MixPanel for an Audio Background process that loses connectivity to the Server (we do this purposely to test audio restart) and when this happens we log lots of back to back MixPanel events, and because the App has no connectivity MixPanel starts to consume more and more CPU bandwidth. MixPanel then will not decrease the CPU consumption until it get's connectivity again, but if this continues for very long iOS will shut down the App and kill it. In this scenario MixPanel ends up crashing the App eventually.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
