### ISSUE TITLE
unable to connect to AB testing server

### ISSUE THREAD

**Issue by ekimia** [mixpanel/mixpanel-swift#301]
everything else is working. Only hint i get with logging on is:
```
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (debug) - codeless event bindings check response format error
```

Using mixpanel swift 2.6.3

**Comment by zihejia** [comment]
hi @ekimia , could you pls try again? If the problem persists, you may contact mixpanel support for further help.

**Comment by zihejia** [comment]
hi @ekimia , do you still have the issue?

**Comment by ekimia** [comment]
@zihejia i chatted with support. Our app uses multiple windows (finance app, need a "curtain" so people can auth in) which hates the AB tester. Submitted a feature request for an SDK method to initialize the connection since right now i have to comment out the window code in order for it to work.

**Comment by zihejia** [comment]
Hi @ekimia could  you pls elaborate on the feature request here?

**Comment by ekimia** [comment]
@zihejia an SDK method to initialize the connection to the AB editor

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
