### ISSUE TITLE
Cannot build for Xcode 10.2.1 Carthage

### ISSUE THREAD

**Issue by michael-mckenna** [mixpanel/mixpanel-swift#308]
Mixpanel Version: 2.6.3
Xcode: 10.2.1
Swift Compiler Version: 4.2
Carthage: 0.33

Terminal output:
```
*** Building scheme "Mixpanel" in MixpanelDemo.xcworkspace
Build Failed:Task failed with exit code 65
```
Bottom of log file (lmk if you need me to send over the full thing):
```
Mixpanel/MiniNotificationViewController.xib: error: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7f9546c7cff0> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7f9546c7d060> scaleFactor=2x'. These intermediate objects were non-nil: (
    "IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)",
    "iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2"
)
    Underlying Errors:
        Description: Failed to find a suitable device for the type IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) with runtime iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2
        Failure Reason: Failed to create new simulator device that matches IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x) for runtime iOS 12.2 (12.2 - 16E226) - com.apple.CoreSimulator.SimRuntime.iOS-12-2 (Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-2)
        Underlying Errors:
            Description: Invalid runtime: com.apple.CoreSimulator.SimRuntime.iOS-12-2

** ARCHIVE FAILED **
```

Oddly enough, only one person on my team is getting the issue. We've tried deleting the Carthage directory in our project, deleting Carthage cache, cleaning build folder, running `carthage update --platform ios --no-use-binaries` and `carthage update --platform ios`.

**Comment by LewinJun** [comment]
I met too. Did you solve it?

**Comment by simonbromberg** [comment]
Seeing similar problem with Xcode 10.3 with CocoaPods (was working fine on Xcode 10.2.1 until I updated today)

**Comment by simonbromberg** [comment]
Seems to have resolved after:

    sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService

On the basis of https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/795 (although I can't be 100% sure right now because I didn't try building right away afterwards)

**Comment by zihejia** [comment]
I'm closing this issue now as it's not directly related to Mixpanel. Please feel free to reopen it if there is still a problem.
