### ISSUE TITLE
SDK not properly identifiying users

### ISSUE THREAD

**Issue by ekimia** [mixpanel/mixpanel-swift#313]
basic example is identifying the user with our internal distinct ID. However subsequent logs do not use it

**Comment by zihejia** [comment]
hi @ekimia , could you provide more information for us to diagnose? sdk version, sample code etc.

**Comment by ekimia** [comment]
sure. we are on 2.6.3. In terms of sample code, there isnt much for this. We have a configure mixpanel function containing the code below thats called when the app is launched.

![image](https://user-images.githubusercontent.com/357513/60843339-35675000-a18b-11e9-97d4-abdd73e7eccd.png)

**Comment by ekimia** [comment]
if it helps id be open to hopping on a screen share, we've been plagued by bad mixpanel issues for a while and we all really want to get this sussed out.

**Comment by zihejia** [comment]
hi @ekimia , i couldn't replicate this problem. You may want to check if `User.current?.uuid` has the desired value. When you say ` subsequent logs do not use it`, what is the distinctID being displayed in your live view report then?

**Comment by zihejia** [comment]
closing this one now, our support team will help you out.
