### ISSUE TITLE
(2.6.3) Won't build after Xcode 13.0 installation

### ISSUE THREAD

**Issue by lardois** [mixpanel/mixpanel-swift#318]
App won't build after installating Xcode 13.0 (over previous latest version & 10.14.5) with following error:

`Pods/Mixpanel-swift/Mixpanel/MiniNotificationViewController.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fa5ab8514d0> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7fa5ab87d810> scaleFactor=2x'. These intermediate objects were non-nil: (
MiniNotificationViewController.xib`

Tried
- Clean Build Folder
- `pod deintegrate` -> `pod install`
- `rm -rf ~/Library/Developer/Xcode/DerivedData/`

with no help.

What might cause this?

**Comment by moheny** [comment]
Have your tried:
`sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService` ?

**Comment by lardois** [comment]
This did the trick, thank you!
