### ISSUE TITLE
SwiftPM support

### ISSUE THREAD

**Issue by michael-mckenna** [mixpanel/mixpanel-swift#320]
Hi,
  [SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager.
  
  Here some articles about SwiftPM:
  
  * [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
  * [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
  * [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
  * [Swift.org: Package Manager](https://goo.gl/E01ufX)
  
  When your component is compatible with SwiftPM add on your `README.md` [![SwiftPM Compatible](https://camo.githubusercontent.com/52e3db230991dda10458295d71c859c34be466b6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5377696674504d2d436f6d70617469626c652d627269676874677265656e2e737667)](https://goo.gl/E01ufX) badge on top and add a section for the installation with SwiftPM.

**Comment by gabrielPeart** [comment]
Super important to add support for Swift Package Manager

**Comment by zihejia** [comment]
Thanks for bringing it up. We will add the SwiftPM support very soon.

**Comment by JonathanDowning** [comment]
Hey @zihejia! 
I was just wondering how SPM support is progressing, have you run into any problems with resources such as storyboard/xib files?

**Comment by RamblinWreck77** [comment]
@zihejia Just checking in, we would love this as well. We're trying to migrate away from Cocoapods to Xcode 11's SPM and mixpanel is the last 3rd party library without support. It appears #325 solves the issue.

**Comment by emisvx** [comment]
Any updates on it? We are also trying to migrate from Carthage to SPM, we would really appreciate if Mixpanel added support for it.

Thanks!

**Comment by RamblinWreck77** [comment]
Any update? This seems like a very minor change (adding 1 swift package file).

**Comment by rodrigoelp** [comment]
I am going to join the petition to have SPM support soon-ish.

**Comment by geertbeskers** [comment]
Is there any update? I'm also waiting for SPM support! Its just a minor implementation.

**Comment by mdoghri** [comment]
+1

**Comment by gabrielPeart** [comment]
+1

**Comment by gsabran** [comment]
+1! @zihejia do you have a sense of when we can expect an update on this?

**Comment by zihejia** [comment]
hi @gsabran We will release it before the Christmas break.

**Comment by rodrigoelp** [comment]
That's awesome @zihejia, looking forward to this Christmas gift :)

**Comment by gsabran** [comment]
<img src="https://media.giphy.com/media/9JrvLb0fnrn7k1ZjhX/giphy.gif" width=50%>

**Comment by zihejia** [comment]
My apologies guys, I should had communicated this earlier. It seems SPM doesn’t have a full support for xib(Bundles and Resources) and mixed swift and objective c code just yet. There are a lot more work than expected for making a workaround. So had to temporarily put it on hold because of other priorities. Will keep an eye on this package resources proposal: https://forums.swift.org/t/draft-proposal-package-resources/29941

**Comment by RamblinWreck77** [comment]
The proposal was accepted!

https://forums.swift.org/t/accepted-with-modifications-se-0271-package-manager-resources/31021

**Comment by gsabran** [comment]
As https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md has been implemented as part of Swift 5.3, when do you think this could be done @zihejia ?

**Comment by bwhiteley** [comment]
Any updates on this? With Xcode 12 released today, I suspect some folks will be keen on moving to SwiftPM soon.

**Comment by sbporter** [comment]
Just completed migration from Carthage to SwiftPM due to their issues with the Xcode 12 xcbuild lipo toolchain. This is the last dependency I need updated. I see there is a pending pull request for support, has it been reviewed? https://github.com/mixpanel/mixpanel-swift/pull/392

**Comment by RamblinWreck77** [comment]
+1

**Comment by piers12** [comment]
Any update? as an iOS dev I am not interested in using cocoapods anymore. Firebase analytics has SPM in beta. Hope you guys can catch up ASAP

**Comment by geertbeskers** [comment]
I am also curious about the progress. It would be nice if we know the time frame it will be realized.

**Comment by zihejia** [comment]
Hi guys, we will be working on this very soon. Please stay tuned.

**Comment by gabrielPeart** [comment]
@zihejia thank you!

Looking forward to it!

**Comment by piers12** [comment]
@zihejia Sorry to be a pain but I really want to use your product and I can't at the moment without SwiftPM support. Any ideas on timeframe?
Thanks

**Comment by zihejia** [comment]
Hi @piers12 , We will release it next week, thanks for the patient.

**Comment by nmtitov** [comment]
Looking forward to getting SPM support!

**Comment by nmtitov** [comment]
> Hi @piers12 , We will release it next week, thanks for your patience.

Can we expect it this week?

**Comment by zihejia** [comment]
Hi guys. we have released [v2.8.0](https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.8.0.) finally has the iOS SPM support! A huge thank you for your contribution and your patience!

The next step is to support for other platforms(appleTV, macOS and watchOS).It looks like SPM does not support multiple targets sharing the common files, we are thinking about splitting the framework into two modules but it still requires some more work. Please stay tuned. In the meantime, please feel free to post any issues or suggestions.

**Comment by RamblinWreck77** [comment]
@zihejia Awesome! Testing it out now! Thanks :)

**Comment by zihejia** [comment]
Hi folks, again many thanks for your support, I will close this one and let's use https://github.com/mixpanel/mixpanel-swift/issues/420 and 
https://github.com/mixpanel/mixpanel-swift/issues/415  to track for the remaining macOS and watchOS supports.
