### ISSUE TITLE
[2.6.5] Crash in archiveToFile's NSKeyedArchiver

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#327]
Hello! We're getting a weird production crash inside Persistence.swift's archiveToFile function. 

It seems like something is blowing up inside NSKeyedArchiver.archiveRootObject's, and I can't reproduce it but we're seeing ~100 crashes a day from it. 

```
Sampled Backtrace (0)#0	(null) in bufferWrite ()
#1	(null) in __CFBinaryPlistWriteOrPresize ()
#2	(null) in -[NSKeyedArchiver finishEncoding] ()
#3	(null) in +[NSKeyedArchiver archiveRootObject:toFile:] ()
#4	0x3409fa8 in closure #1 in static Persistence.archiveToFile(_:object:token:) 
#5	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#6	0x3385e58 in +[ExceptionWrapper try:catch:finally:] 
#7	0x340d8f0 in specialized static Persistence.archiveToFile(_:object:token:)
#8	(null) in closure #2 in closure #1 in MixpanelInstance.track(event:properties:) ()
#9	0x340e7e0 in closure #1 in ReadWriteLock.read(closure:)
#10	(null) in partial apply for thunk for @callee_guaranteed () -> () ()
#11	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#12	(null) in _dispatch_client_callout ()
#13	(null) in _dispatch_sync_invoke_and_complete ()
#14	0x33da058 in closure #1 in MixpanelInstance.track(event:properties:)
#15	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#16	(null) in _dispatch_call_block_and_release ()
#17	(null) in _dispatch_client_callout ()
#18	(null) in _dispatch_lane_serial_drain ()
#19	(null) in _dispatch_lane_invoke ()
#20	(null) in _dispatch_workloop_worker_thread ()
#21	(null) in _pthread_wqthread ()

```

Taking a peek at the source code it's not obvious to me what the problem is, but I'm suspicious of all the objc_sync_enter/exit mixed with ExceptionWrapper.try and archiveRootObject. 

I think I see what you're trying to do here with the sync locks, would you consider switching to a more modern serial queue + async dispatch model? That would get rid of the need for locks and *might* fix the issue. I'll get a PR up and reference here and see if you like it.

**Comment by RamblinWreck77** [comment]
#328 up

**Comment by zihejia** [comment]
Hi @RamblinWreck77 , thanks for bringing it up and again thanks so much  for your contribution to Mixpanel SDK.  This crash doesn't seem to be caused by a race condition more of a corrupted archive file, so i don't think changing  objc_sync_enter/exit will help in this case. However, I agree we should use queue instead. I will take care of it and submit a PR based on your idea.

~100 crashes a day seems a lot, how do you compare it to the previous version?  Could you share a little bit about how events being tracked that cause this crash if you know the answer?

**Comment by zihejia** [comment]
Do you have a more complete crash log that showing the crash type or crash code? Sometime, if the corruption happens during the archiving/unarchiving, ExceptionWrapper will catch it and prevent it from a real crash but it will still show up in the stack trace.

**Comment by RamblinWreck77** [comment]
Crap! My apologies, these are energy related terminations and not crashes. I was curious why I didn't see this in our normal crash logging and noticed the xcode organizer tab was energy not crashes.

Here's more details:

```
iOS: 12.4 (16G77)
Device: iPhone XR
Type: High CPU Usage
Detail: 144 seconds cpu time over 6 seconds (2400% cpu average), exceeding limit of 80% cpu over 180 seconds
```

Which seems quite high. I'm not sure how an archive could chew up so much CPU. 


Here's another instance:


```
iOS: 12.4 (16G77)
Device: iPhone 8 Plus
Type: High CPU Usage
Detail: 144 seconds cpu time over 6 seconds (2400% cpu average), exceeding limit of 80% cpu over 180 seconds
```

```
Sampled Backtrace (0)#0	(null) in <unsymbolicated symbol> ()
#1	(null) in $ss26_SwiftDeferredNSDictionaryC10bridgeKeyss20__BridgingHashBufferCSgyF ()
#2	(null) in $ss26_SwiftDeferredNSDictionaryC10getObjects_7andKeys5countySpyyXlGSg_AGSitF ()
#3	(null) in $ss26_SwiftDeferredNSDictionaryC10getObjects_7andKeys5countySpyyXlGSg_AGSitFToTm ()
#4	(null) in -[NSDictionary(NSDictionary) encodeWithCoder:] ()
#5	(null) in _encodeObject ()
#6	(null) in -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] ()
#7	(null) in -[NSDictionary(NSDictionary) encodeWithCoder:] ()
#8	(null) in _encodeObject ()
#9	(null) in -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] ()
#10	(null) in _encodeObject ()
#11	(null) in +[NSKeyedArchiver archiveRootObject:toFile:] ()
#12	0x167dfa8 in closure #1 in static Persistence.archiveToFile(_:object:token:)
#13	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#14	0x15f9e58 in +[ExceptionWrapper try:catch:finally:]
#15	0x16818f0 in specialized static Persistence.archiveToFile(_:object:token:) at /Users/Eric/iOSDev/fixd/Pods/Mixpanel-swift/Mixpanel/Persistence.swift:153
#16	(null) in closure #2 in closure #1 in MixpanelInstance.track(event:properties:) ()
#17	0x16827e0 in closure #1 in ReadWriteLock.read(closure:) 
#18	(null) in partial apply for thunk for @callee_guaranteed () -> () ()
#19	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#20	(null) in _dispatch_client_callout ()
#21	(null) in _dispatch_sync_invoke_and_complete ()
#22	0x164e058 in closure #1 in MixpanelInstance.track(event:properties:)
#23	(null) in thunk for @escaping @callee_guaranteed () -> () ()
#24	(null) in _dispatch_call_block_and_release ()
#25	(null) in _dispatch_client_callout ()
#26	(null) in _dispatch_lane_serial_drain$VARIANT$armv81 ()
#27	(null) in _dispatch_lane_invoke$VARIANT$armv81 ()
#28	(null) in _dispatch_workloop_worker_thread ()
#29	(null) in _pthread_wqthread ()
```

**Comment by RamblinWreck77** [comment]
One potential cause: Our app wakes up in the background due to significant location changes. We get 2.5-3.4 million of these a day, and sometimes when we wake up the phone is in a locked state such that "protected data is unavailable".

In these situations we can't run, and simply go back to sleep. I noticed in NSKeyedArchiver:

```
Archives an object graph rooted at a given object by encoding it into a data object then atomically writes the resulting data object to a file at a given path, and returns a Boolean value that indicates whether the operation was successful.
```

Maybe it's hanging because disk/IO is unavailable and failing in some way that causes a CPU tight loop?

**Comment by RamblinWreck77** [comment]
The top answer here seems interesting:

https://stackoverflow.com/questions/47960353/crash-while-archiving-data-by-nskeyedarchiver

**Comment by zihejia** [comment]
This particular "crash" around archive does seem to be the same as we have previously being identified as threading issues. I suspect the high energy/cpu is not caused by the archive itself but more likely to be the other way around, the archive has been terminated by iOS before finishes due to the overall high energy/cpu usage from other threads. There is also no evidence to show objc_sync_enter/exit consume high cpu, but we will change it for sure.

**Comment by zihejia** [comment]
sorry i mean does Not seem to the same.

**Comment by RamblinWreck77** [comment]
Interesting, well I'm curious if the issue goes away with the queue change. Thanks for following up so quickly on this!

**Comment by zihejia** [comment]
Hi @RamblinWreck77 , 2.6.6 should be able to fix this issue. Please feel free to reopen it if not. 
https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.6.6
