### ISSUE TITLE
Swift 3.01 breaks mix panel (Carthage)

### ISSUE THREAD

**Issue by alessandro-martin** [mixpanel/mixpanel-swift#33]
The latest Swift 3.01 included in Xcode 8.1GM breaks mix panel. The framework that Carthage fetches is compiled with Swift 3.0 and cannot be used while trying to force compilation with 
`carthage update --platform iOS --no-use-binaries`
fails with errors and warnings.

**Comment by yarneo** [comment]
Hi @alessandro-martin , as much as we want to support every new release of Swift/Xcode, it would be a lot of work for us to do so, and would leave us with a mess with multiple releases for each version. Therefore we currently do not support any beta products. Having said that, we will definitely fully support it once it's released.
Thanks!

**Comment by alessandro-martin** [comment]
I understand your policy but I also would like to point out that iOS 10.1 is final and Xcode 8.1GM is a gold master, not a beta.

**Comment by yarneo** [comment]
I agree. However if we were to cut a new release that supports the GM, we would break the current release that most of our users are using. It would be unfair for us to force them to upgrade to a GM version if they update their SDK version. I will keep it on my radar to push an upgrade the day the new Xcode is released. In the meanwhile, if it is breaking your development, I recommend forking our SDK and making the small changes to help solve the issue. If you choose to do so, a PR would be most welcome :)

**Comment by yarneo** [comment]
hey @alessandro-martin , we just tested out carthage with the new release and it is compiling ok for us (there are just more warnings than before). Would you be able to provide us the error you are getting? Thanks!

**Comment by alessandro-martin** [comment]
Sorry, I have already removed MixPanel from the project. Maybe next time, thanks anyways.

**Comment by yarneo** [comment]
No worries, we are here to help if you need any more assistance. Thanks!
