### ISSUE TITLE
JSONSerialization crash when using Mixpanel/Alamofire

### ISSUE THREAD

**Issue by theMeatloaf** [mixpanel/mixpanel-swift#336]
For some strange reason after installing the SDK with cocoapods, I get a bad_access crash when parsing json using `JSONSerialization`.  Keep in mind this happens even if I don't initialize, import, or use the Mixpanel lib in any way....I've tried making it work for days with no luck.  You can see in the screenshot that the data object is not nil and has bytes, and I've even tried it with hard coded json and I still get a crash.

Is there some kind of Json parsing swizzling or something going on that could cause this?  Or maybe something related to threading?  I looked through the code a bit and couldn't see anything like that but maybe I'm missing something.  Any help is appreciated....

![Screen Shot 2019-12-13 at 4 02 52 PM](https://user-images.githubusercontent.com/1868598/70839574-39df0700-1dc2-11ea-8f88-c3bbe1c3707d.png)

**Comment by zihejia** [comment]
hi @theMeatloaf  if you don't initialize, import or use Mixpanel lib, the crash might not  be from Mixpanel. Have you tried clean all your built cache. Try uninstall Mixpanel pod and reinstall it, see what happens. I might need more information for diagnosing this issue.

**Comment by theMeatloaf** [comment]
yeah I've tried just about all the typical tricks that would normally fix an issue like this, but nothing seemed to work.

I wonder if its related to cocoapods....I can try installing the library manually to see if that fixes it.

**Comment by zihejia** [comment]
hi @theMeatloaf , did you end up fixing the problem. Sorry for the late response.

**Comment by zihejia** [comment]
hi @theMeatloaf, I'm closing this one now, please feel free to reopen it if the problem still exists.

**Comment by theMeatloaf** [comment]
Hey yeah I'm not sure exactly what the cause of this was, but I believe my fix was to allow json fragments in my network logging layer.  Not sure why that became required when I added the mixpanel SDK, but I think its safe to close this unless anyone else has similar issues.
