### ISSUE TITLE
Edited developer tweaks are ignored without experiment reset (A/B tests)

### ISSUE THREAD

**Issue by nikolayev** [mixpanel/mixpanel-swift#339]
I'm still facing the same issue that was described in #302. 
Some backstory. I've faced an issue when unless we reset an experiment on Mixpanel website - edited tweaks are not received on the client side. After digging further I've found that we do actually receive edited tweaks, but we discard them because we think that change didn't happen.

#305 didn't really address the issue. What changed:
```
let newVariants = parsedVariants.subtracting(runningVariants)
decideResponse.newVariants = newVariants
self.ABTestingInstance.variants = newVariants.union(runningVariants)
```
Became 
```
decideResponse.newVariants = parsedVariants.subtracting(runningVariants)
self.ABTestingInstance.variants = parsedVariants.subtracting(runningVariants).union(runningVariants)
```

Issue still arise because `Set.union()` doesn't replace variant with old tweaks with the new tweaks variant. Replace doesn't happen because `Variant.isEqual` doesn't include tweaks into comparison, e.g:
```
Variant1: 
{ 
    "notifications":[ ],
    "variants":[ 
        { 
            "tweaks":[ 
                { 
                    "name":"Tweak name",
                    "encoding":"@",
                    "default":"",
                    "maximum":null,
                    "value":"value1",
                    "minimum":null,
                    "type":"string"
                }
            ],
            "actions":[ ], "id":205809, "experiment_id":93657
        }
    ], "automatic_events":false, "integrations":[ ]
}

Variant 2:
{ 
    "notifications":[ ],
    "variants":[ 
        { 
            "tweaks":[ 
                { 
                    "name":"Tweak name",
                    "encoding":"@",
                    "default":"",
                    "maximum":null,
                    "value":"value2",
                    "minimum":null,
                    "type":"string"
                }
            ],
            "actions":[ ], "id":205809, "experiment_id":93657
        }
    ], "automatic_events":false, "integrations":[ ]
}
```
Difference between those 2 Variants is that they have tweaks with same name but different values. Because `Variant.isEqual` includes only `ID` and `actions` comparison - **Variant1** will be considered as equal to **Variant2**. Going further - `VariantTweak.isEqual` doesn't compare values, so `VariantTweak(name: "Foo", value: 1)` will equal to `VariantTweak(name: "Foo", value: 2)`(sorry for pseudocode, don't want to make this comment larger than it is). 

Resetting experiment via Mixpanel website bumps `Variant.ID` so `isEqual` check begins to work and edited values are fetched successfully.

Question arises here: is it a **by-design** behavior that we can't change experiment values on-the-fly without resetting the experiment? If not - we need to do 2 things here:
1) Update `Variant.isEqual` to compare not only `ID` and `actions` but also `tweaks` property
2) Update `VariantTweak.isEqual` to compare not only `name` but also `value`

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
