### ISSUE TITLE
UI API called from background thread: -[UIApplication setNetworkActivityIndicatorVisible:]

### ISSUE THREAD

**Issue by JMCPH** [mixpanel/mixpanel-swift#349]
<img width="957" alt="Screenshot 2020-02-24 at 22 59 21" src="https://user-images.githubusercontent.com/5514628/75194960-5cde4d80-5759-11ea-84c8-2ada5681954c.png">

These two functions are called on the background thread. Please move them into the main thread.

Thanks :)

**Comment by zihejia** [comment]
Hi @JMCPH it seems you are not using the latest Objective-C sdk version, would you please try the latest version: https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.6.0, if you find any issues, please open an new issue in Objective-C repo instead: https://github.com/mixpanel/mixpanel-iphone/issues. thanks!
