### ISSUE TITLE
Add Swift package manager support

### ISSUE THREAD

**Issue by SmartAkashNara** [mixpanel/mixpanel-swift#352]
Add Swift package manager support

![Screenshot 2020-03-04 at 12 08 33 PM](https://user-images.githubusercontent.com/61772249/75851752-83168400-5e10-11ea-91af-9973600f125c.png)

**Comment by pushchris** [comment]
Would love to see support for this

**Comment by ruipfcosta** [comment]
+1

**Comment by zihejia** [comment]
Duplicated with https://github.com/mixpanel/mixpanel-swift/issues/320, let's use it to track instead, thanks guys for bringing it up.
