### ISSUE TITLE
[2.7.0] App not building with Mixpanel

### ISSUE THREAD

**Issue by danielmarkspaybox** [mixpanel/mixpanel-swift#357]
I have updated to Swift 5 and updated the mixpanel pod to the latest, but my app isn't building. Please tell me how to fix this:
<img width="1792" alt="Screen Shot 2020-04-02 at 17 57 11" src="https://user-images.githubusercontent.com/63059950/78264194-871aec00-750b-11ea-8bb8-4e03caf331e6.png">

**Comment by zihejia** [comment]
hi @danielmarkspaybox , the issue has been fixed in v2.7.1. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.7.1  I'm closing this one now, please feel free to reopen it if the problem still exists.
