### ISSUE TITLE
Pod install not working

### ISSUE THREAD

**Issue by AmbroiseCollon** [mixpanel/mixpanel-swift#36]
This is what I get when I try to do a pod install => 
`[!] Unable to find a specification for 'Mixpanel-swift'`

I've been using cocoa pods a lot in my project and it works perfectly.

**Comment by yarneo** [comment]
Thanks @AmbroiseCollon , sorry you are seeing this. May I ask what CocoaPods version you are using? I would recommend to use the latest (v1.1.1). Also, by researching your error message, it seems that there is a problem with your pod master repo. try issuing the command 'pod setup' and let me know if that helps.

**Comment by AmbroiseCollon** [comment]
The setup solved the issue thanks !

**Comment by yarneo** [comment]
Awesome, glad to help!
