### ISSUE TITLE
mixpanel-swift crashes with Tabman pod

### ISSUE THREAD

**Issue by stevepetersen** [mixpanel/mixpanel-swift#372]
mixpanel-swift: 2.7.2
Tabman 2.9.0

Repro steps:  do the 4-finger method for connecting to "Developer Tweaks" on Mixpanel web.  The crash occurs within the mixpanel mp_targetActions() method.  See attached screenshot.
<img width="1609" alt="Screen Shot 2020-05-07 at 3 43 14 PM" src="https://user-images.githubusercontent.com/10552645/81351573-82e96d80-9079-11ea-98b6-25af72a09b36.png">

Could not cast value of type 'Tabman.TMBarButtonInteractionController' (0x10a132c60) to 'Swift.AnyHashable' (0x1e4f6eee8).
2020-05-07 15:31:49.251727-0700 Playlist[6797:1275627] Could not cast value of type 'Tabman.TMBarButtonInteractionController' (0x10a132c60) to 'Swift.AnyHashable' (0x1e4f6eee8).

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more info](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
