### ISSUE TITLE
Support for Array<Optional<Double>>

### ISSUE THREAD

**Issue by heestand-xyz** [mixpanel/mixpanel-swift#375]
So the cast succeeds, tho I get a runtime crash...
```
let values: [Double?] = [nil, 0.0, 1.0]
if let mix: MixpanelType = values as? MixpanelType {
    print(mix)
}
```
> Conditional cast from '[Double?]' to 'MixpanelType' always succeeds

`Assertion failed: Property values must be of valid type (MixpanelType). Got Array<Optional<Double>>: file /Users/hexagons/App/Pods/Mixpanel-swift/Mixpanel/MixpanelType.swift, line 233`

**Comment by jaredmixpanel** [comment]
@heestand-xyz we've added support for optional MixpanelType in v2.10.0
