### ISSUE TITLE
Crashed: CTTelephonyNetworkInfo

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [mixpanel/mixpanel-swift#376]
Hello,

I use`Mixpanel-swift` v2.7.2. This crash has happened in a customer's device (iPhone XS Max running iOS 13.4.1). I got a crash report with following info.

> MixpanelInstance.swift - Line 673
> MixpanelInstance.setCurrentRadio() + 673

> Crashed: CTTelephonyNetworkInfo
> 0  libswiftCore.dylib             0x19299b148 swift_getObjectType + 40
> 1  libswiftCore.dylib             0x192949910 unwrapExistential(swift::OpaqueValue*, swift::TargetExistentialTypeMetadata<swift::InProcess> const*, swift::OpaqueValue*&, swift::TargetMetadata<swift::InProcess> const*&, bool&, bool&) + 88
> 2  libswiftCore.dylib             0x1929485d4 swift_dynamicCastImpl(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*, swift::DynamicCastFlags) + 1924
> 3  libswiftFoundation.dylib       0x1bb7693fc closure #2 in static Dictionary._forceBridgeFromObjectiveC(_:result:) + 512
> 4  libswiftFoundation.dylib       0x1bb7c2f08 _NativeDictionary.init(_unsafeUninitializedCapacity:allowingDuplicates:initializingWith:) + 292
> 5  libswiftFoundation.dylib       0x1bb75dc8c static Dictionary._unconditionallyBridgeFromObjectiveC(_:) + 892
> 6  Mixpanel                       0x10377c5b0 MixpanelInstance.setCurrentRadio() + 673 (MixpanelInstance.swift:673)
> 7  Mixpanel                       0x103784a20 @objc MixpanelInstance.setCurrentRadio() + 4375480864
> 8  CoreFoundation                 0x184d941e0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
> 9  CoreFoundation                 0x184d94230 ___CFXRegistrationPost1_block_invoke + 68
> 10 CoreFoundation                 0x184d93520 _CFXRegistrationPost1 + 396
> 11 CoreFoundation                 0x184d931d4 ___CFXNotificationPost_block_invoke + 92
> 12 CoreFoundation                 0x184d0c678 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1420
> 13 CoreFoundation                 0x184d92b14 _CFXNotificationPost + 1260
> 14 Foundation                     0x1850f9f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
> 15 CoreTelephony                  0x1896e95d4 -[CTTelephonyNetworkInfo updateLegacyRat:] + 88
> 16 CoreTelephony                  0x1896e94c8 -[CTTelephonyNetworkInfo updateRat:descriptor:] + 548
> 17 CoreTelephony                  0x1896e91e8 -[CTTelephonyNetworkInfo queryRatForDescriptor:] + 392
> 18 CoreTelephony                  0x1896e7edc -[CTTelephonyNetworkInfo connectionStateChanged:connection:dataConnectionStatusInfo:] + 100
> 19 CoreFoundation                 0x184e42d14 __invoking___ + 148
> 20 CoreFoundation                 0x184d0bde8 -[NSInvocation invoke] + 400
> 21 CoreFoundation                 0x184d0ca10 -[NSInvocation invokeWithTarget:] + 80
> 22 CoreTelephony                  0x1896f0dac void dispatch::async<-[CoreTelephonyClientMux sink:handleNotification:]::$_2>(dispatch_queue_s*, std::__1::unique_ptr<-[CoreTelephonyClientMux sink:handleNotification:]::$_2, std::__1::default_delete<-[CoreTelephonyClientMux sink:handleNotification:]::$_2> >)::'lambda'(void*)::__invoke(void*) + 40
> 23 libdispatch.dylib              0x184adc33c _dispatch_client_callout + 20
> 24 libdispatch.dylib              0x184ae285c _dispatch_lane_serial_drain + 568
> 25 libdispatch.dylib              0x184ae3290 _dispatch_lane_invoke + 400
> 26 libdispatch.dylib              0x184aec928 _dispatch_workloop_worker_thread + 584
> 27 libsystem_pthread.dylib        0x184b43714 _pthread_wqthread + 276
> 28 libsystem_pthread.dylib        0x184b499c8 start_wqthread + 8

**Comment by JMCPH** [comment]
We get the same crash on our app. When can we expect a fix?

**Comment by zihejia** [comment]
yes, we will take a look at this one.

**Comment by zihejia** [comment]
it's duplicated with https://github.com/mixpanel/mixpanel-swift/issues/367, so let's use that one to track instead.
