### ISSUE TITLE
How can I disable tracking until signed in?

### ISSUE THREAD

**Issue by IsaiahJTurner** [mixpanel/mixpanel-swift#380]
We'd like to continue using auto events (but only after signed in) and they currently cause empty users to be created because they track before sign in. Alias is not an option for us. We don't want anonymous users because Mixpanel charges per user and it causes costs to increase when users sign out.

We are trying to get rid of all the random identifiers the lib wants to generate so it will only use user IDs. Right now, we set annonymousId to nil before calling identify which seems to help with creating multiple Ids. We also call reset() on logout and set disableAutomaticEvents on logout (then reenable after calling identify during login).

Is there anything I'm missing? This use case doesn't seem to be documented anywhere.

**Comment by zihejia** [comment]
hi @IsaiahJTurner , sorry for late response. If I understand correctly, you only need to start tracking once the user signed in?
Are the api `optOutTracking()` and `optInTracking(distinctId:properties:)` able to help you?
https://mixpanel.github.io/mixpanel-swift/Classes/MixpanelInstance.html#/s:8Mixpanel0A8InstanceC13optInTracking10distinctId10propertiesySSSg_SDySSAA0A4Type_pGSgtF

**Comment by zihejia** [comment]
Hi @IsaiahJTurner , I'm closing this one now since it's not a SDK issue but you are welcome to contact Mixpanel support for further assistant.
