### ISSUE TITLE
MixpanelInstance.setCurrentRadio() Crash

### ISSUE THREAD

**Issue by jackjpark** [mixpanel/mixpanel-swift#386]
My App is crashing on `MixpanelInstance.setCurrentRadio()`

The stack trace only includes `@objc MixpanelInstance.setCurrentRadio()`

I am on the latest SDK and it appears to worsen rather than improve over the last couple of releases

Can you advise as to a fix for this issue? as it is the number 1 contributor to my apps crash rate

Thanks

**Comment by RamblinWreck77** [comment]
Check out #367

**Comment by zihejia** [comment]
Thanks for bringing this up. Pls use #367 to track. Closing this one now.
