### ISSUE TITLE
Crash on MixpanelInstance.flush(completion:)

### ISSUE THREAD

**Issue by navyseai** [mixpanel/mixpanel-swift#387]
Im having a crash on MixpanelInstance.flush(completion:)

MixPanel 2.7.1
IPhone XR

line 1168 - self.eventsQueue = flushEventsQueue + shadowEventsQueue

seems some sort of issue with memory allocation

**Comment by zihejia** [comment]
hi @navyseai , could you paste the full crash log?

**Comment by zihejia** [comment]
hi @navyseai , please try our latest version v2.7.6. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.7.6 It has several critical fixes about concurrency issues since 2.7.1. I'm closing this one now, please feel free to reopen it if the problem still exists.
