### ISSUE TITLE
Qucik question about 2.7.5

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#395]
Just checked out the diffs from 2.7.4 -> 2.7.5 and I'm glad to see the library moving away from objc_sync's towards dispatch queues!!!

A few quick questions: 

-For the new queues (and all, really), would it be wise to assign them a QoS of .utility? Since this is a background process we probably don't want any of these events getting serviced on UI-sensitive main.

-I shouldn't *technically* be necessary, but I've found it's best practice to capture objects when doing .sync and .async calls to another queue. 

```
let thing = Thing()
myQueue.sync { [thing] in
    thing.doSomething()
}
```

AFAIK it costs nothing and can save some headaches down the road when weird, nonsensical BAD_ACCESS crashes start showing up. 

Thanks for another update :)

**Comment by zihejia** [comment]
hi @RamblinWreck77 , thanks for pointing it out and I've added it to the backlog. I will change it in the next release by using QoS of .utility. However for capture list, there is still a performance cost, unless it's really necessary I would be careful to add them.
