### ISSUE TITLE
Opt In to tracking not working

### ISSUE THREAD

**Issue by jbelkins** [mixpanel/mixpanel-swift#398]
I'm running latest Mixpanel-swift.

When I opt out with `Mixpanel.mainInstance().optOutTracking()`, Mixpanel opts out as you would expect - my client sends no further events or updates to Mixpanel.
But when I try to opt back in with `Mixpanel.mainInstance().optInTracking()`, Mixpanel updates (events, profile updates, etc.) do not resume.

Is there something else I need to be doing?

**Comment by zihejia** [comment]
Hi @jbelkins , I'm very sorry about the late response, do you still have the problem? We couldn't replicate it.

**Comment by jbelkins** [comment]
We're actually using Segment's SDK to integrate with Mixpanel now.  If you can't reproduce, then you can close this issue.

**Comment by zihejia** [comment]
Thanks @jbelkins !
