### ISSUE TITLE
iOS 14 Deprecations of archivedData/unarchiveObject

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#402]
Just a heads up, xcode 12 is reporting:

```
NSKeyedUnarchiver.unarchiveObject

NSKeyedArchiver.archivedData

NSKeyedArchiver.archiveRootObject

MixpanelInstance.telephonyInfo.subscriberCellularProvider?.carrierName
```

as deprecated. We'll be moving to iOS13 minimum soon and just wanted to make sure this was on your radar :) 

Thanks for everything!

**Comment by zihejia** [comment]
hi @RamblinWreck77 , yes, I will address them. Thanks for reaching out.

**Comment by zihejia** [comment]
Hi @RamblinWreck77 , we have updated the apis in [2.8.3](https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.8.3). I'm closing this issue now but pls feel free to reopen it if you find any issues. Thanks again for bringing this up.
