### ISSUE TITLE
Quotes added to string in an array

### ISSUE THREAD

**Issue by akivlis** [mixpanel/mixpanel-swift#410]
If tracking an `event` with a property where the `MixpanelType` is `[String]` , there are `""` added to the string in Mixpanel.

The expected output in Mixpanel is `[a, b, c]`, but the actual output is `["a", "b", "c"]`. 

This works correctly if a single `string` is sent. As soon as it's inside of an array, it adds additional `""`.

**Comment by jaredmixpanel** [comment]
hi @akivlis, apologies for the late response. Unlike individual String properties, Strings inside of List properties are displayed with quotes around them in the Mixpanel UI, but the quotes aren't actually encoded in the raw data of the string. You would only need to search for My List Property contains `a`, `b` or `c` without quotes. If that doesn't resolve your issue, please feel free to re-open with more information.

**Comment by akivlis** [comment]
Hi, thanks for the reply. The problem is, that we have inconsistent data coming from iOS and Android. So, the android does not add the `""` whereas the iOS does. My intention is just to have the same output for both platforms, so either to have a list of values `[a, b, c]` or a list of strings ["a", "b", "c"]. I'm not sure whether I'm doing something wrong or it is the desired behaviour. Pls, see the screenshot attached with the data coming from Android (first two lines) and iOS (third line). Is there something I can do about it? 

Thank you 🙏  


<img width="438" alt="Screenshot 2021-02-19 at 10 04 39" src="https://user-images.githubusercontent.com/32448186/108491622-6cc53a80-72a4-11eb-9305-905986f3abf1.png">

**Comment by jaredmixpanel** [comment]
@akivlis check the track calls that are sending this property closely. it looks like you may be converting the array to a string representation before sending it as a property in one case and not the other. there should be no difference between Android and iOS in this respect, my guess is you're passing the value into this property as a string on one platform (probably Android) and as an array on the other.

**Comment by putrarolli93** [comment]
> Hi, thanks for the reply. The problem is, that we have inconsistent data coming from iOS and Android. So, the android does not add the `""` whereas the iOS does. My intention is just to have the same output for both platforms, so either to have a list of values `[a, b, c]` or a list of strings ["a", "b", "c"]. I'm not sure whether I'm doing something wrong or it is the desired behaviour. Pls, see the screenshot attached with the data coming from Android (first two lines) and iOS (third line). Is there something I can do about it?
> 
> Thank you 🙏
> 
> <img alt="Screenshot 2021-02-19 at 10 04 39" width="438" src="https://user-images.githubusercontent.com/32448186/108491622-6cc53a80-72a4-11eb-9305-905986f3abf1.png">

hi, i get same issue with you. 
iOS app give output ["one","two"]

android give [one,two]

so whats wrong @jaredmixpanel ?

`    fun filterSearchFromDoctorList(
        filter: MutableList<String> = mutableListOf(),
        hospitalName: String = ""
    ) {
        val props = JSONObject()
        props.put("Active filters", filter)
        props.put("Hospital Unit", hospitalName)
        mixPanel.track("Filter - Doctor List", props)
    }`

**Comment by nurirppan** [comment]
has this issue been resolved? @jaredmixpanel
