### ISSUE TITLE
Unable to connect to AB Testing server

### ISSUE THREAD

**Issue by RushanB** [mixpanel/mixpanel-swift#416]
Seems similar to this issue https://github.com/mixpanel/mixpanel-swift/issues/301 but I followed the docs to run an AB test in my project, I can see the tweak and enable/ disable it when I have my iphone wired while creating the ab test through the mixpanel portal but I am unable to see changes for all other users when running live. This is what I am getting in my log

[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (debug) - variants check response format error
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available triggered notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 1 new codeless bindings out of [UIControl Codeless Binding: Job Confirmed for <Mixpanel.ObjectSelector: 0x6000014d85a0>]
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new variants out of []
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide cache found, skipping network request
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available triggered notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new codeless bindings out of [UIControl Codeless Binding: Job Confirmed for <Mixpanel.ObjectSelector: 0x6000014d85a0>]

**Comment by zihejia** [comment]
hi @RushanB , sorry for the late response. From the log, it seems the server was able to be connected but has some error trying to parse the variants. I'm thinking what are your settings in the A/B testing server, do you still have the problem?

**Comment by RushanB** [comment]
@zihejia It is very odd since it is working in the Staging server but in the Production server it doesn't update the views. Which specific settings are you interested in & yes it is still not working in the production server.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
