### ISSUE TITLE
Can't find shared initializer function in latest Mixpanel Pod: Mixpanel.initialize(token: ...)

### ISSUE THREAD

**Issue by zkhalapyan** [mixpanel/mixpanel-swift#417]
Following the examples on Mixpanel's Swift setup, I am using the `initialize(..)` function. However, it seems like this has either been removed, deprecated or renamed. Can you please advice. 

```
// Getting error, "Argument passed to call that takes no arguments"
Mixpanel.initialize(token: "...")
```

I am on Xcode 12, installing latest Mixpanel via CocoaPods. 

Is the correct option to use `Mixpanel.sharedInstance(withToken: mixpanelToken)`?

**Comment by zkhalapyan** [comment]
Oh, was using `pod 'Mixpanel'` instead of `pod 'Mixpanel-Swift'`. There is no way to prevent this mistake from happening yeh?

**Comment by zihejia** [comment]
hi @zkhalapyan , for our Swift SDK, we recommend using SPM to integrate so it's unlikely to have this kind of mistake. 
In Xcode, select File > Swift Packages > Add Package Dependency.
Follow the prompts using the Github URL for Mixpanel Swift library and a minimum semantic version of v2.8.0
