### ISSUE TITLE
Provide an ability to cancel a timedEvent

### ISSUE THREAD

**Issue by kohtenko** [mixpanel/mixpanel-swift#419]
At the moment the only public way of cancelling a timed event is cancelling all timed events using `clearTimedEvents()`, but this is not always safe. For example, if some measurement block didn't succeed, I'd rather prefer to cancel the timed event and report an error. If I cancel all timed events I can't be sure I don't jeopardize another concurrent timed event tracking.

**Comment by jaredmixpanel** [comment]
@kohtenko this functionality has been added in v2.9.0
