### ISSUE TITLE
Deeplink not working on Killed State

### ISSUE THREAD

**Issue by maughray** [mixpanel/mixpanel-swift#424]
I'm trying to send a rich push notification with a button that opens a URL. It actually works when application is active or in background, but nothing is called when application is killed. I'm using Mixpanel-swift 2.8.1.

When app is opened by clicking this button:
launchOptions is nil

these functions are NOT called:
`func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool`
`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool`
`func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool`

And even this function is not called: 
`func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)`
However, it is called when application is not killed.

How can i handle deeplink when application is killed?
Thanks.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more info](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
