### ISSUE TITLE
Make Logging, LogMessage, Logger, and addLogging(_:) public?

### ISSUE THREAD

**Issue by nflahavan** [mixpanel/mixpanel-swift#426]
Hey guys!

Like the title says, I'm curious if you'd be open to making `Logging`, `LogMessage`, `Logger`, and `addLogging(_:)` public? All I want to do is listen in to all those great log messages that have been added to the project by adding my own object conforming to `Logging`. What do you think? I'd be happy to do the work if you're open to the idea.

Thanks!

**Comment by zihejia** [comment]
hi @nflahavan , we have no plan to make this public for now unless there are many requests. The Logger is only used internally and we want to keep the SDK as lean as possible. But you are welcome to fork it or modify any part of the code to tailor to your need.
