### ISSUE TITLE
Sending many events in a row causes OOM crash

### ISSUE THREAD

**Issue by armandsLa** [mixpanel/mixpanel-swift#429]
When sending many(100-200) events in a row, SDK ramps up memory usage above 400mb. This eventually causes OOM crash.

**Comment by zihejia** [comment]
hi @armandsLa , we will have a look. Could you please share the crash log? Is the crash happened during debugging or in production? If it's possible, could you share a code snippet for how you are sending 200 events in a row?

**Comment by armandsLa** [comment]
Unfortunately I don't have the crash logs.

This issue occurs in both development and production versions. Events were captured by mistakenly adding on of our endpoints to [this](https://developer.apple.com/documentation/uikit/uicollectionviewdropdelegate/2897375-collectionview) function. When user drags an UI element, this function is being called on every position change.

**Comment by tokorom** [comment]
I've seen a similar problem in my app.

If I try to send a lot of events to Mixpanel while offline, the memory of the attached Stack Trace may temporarily stacks more and more. In my hand, I confirmed that this Malloc 2.80 MiB stacks about 600MB.

![memory-log](https://user-images.githubusercontent.com/629993/107328639-5e339200-6af2-11eb-809d-543b9707dff8.png)

**Comment by TimPapler** [comment]
We have actually exactly the same stack when we get crash/app suspended by iOS CPU usage watchdog reports from production. 

> 144 seconds cpu time over 170 seconds (85% cpu average), exceeding limit of 80% cpu over 180 seconds

This is a bit of problem since we can't just limit our users to use app online only. 🙈

**Comment by zihejia** [comment]
hi @TimPapler , we have been actively working on this issue for now. Will launch a new release by the end of this month. Sorry for the inconvenience.

**Comment by TimPapler** [comment]
> hi @TimPapler , we have been actively working on this issue for now. Will launch a new release by the end of this month. Sorry for the inconvenience.

Hey, this is great news, thank you.

**Comment by jaredmixpanel** [comment]
@armandsLa @tokorom @TimPapler We have a new beta release that addresses this issue if you'd like to try it out here: https://github.com/mixpanel/mixpanel-swift/releases/tag/v3.0.0.beta.4 (Please note though the beta release does **not** include Messages & Experiments functionality)

**Comment by jaredmixpanel** [comment]
Instructions for installing the beta branch are here: https://github.com/mixpanel/mixpanel-swift/tree/3.0.0.beta#installation

**Comment by TimPapler** [comment]
> @armandsLa @tokorom @TimPapler We have a new beta release that addresses this issue if you'd like to try it out here: https://github.com/mixpanel/mixpanel-swift/releases/tag/v3.0.0.beta.4 (Please note though the beta release does **not** include Messages & Experiments functionality)

At the moment we still depend on Messages functionality so I am not sure if I can test it right now. Will this issue be resolved  in pre 3.0+ Mixpanel frameworks or is it 3.0+ only? I know we will have to migrate Messages functionality to 3rd party partner before the end of the year but still.

**Comment by jaredmixpanel** [comment]
@TimPapler the switch to SQLite will be 3.0+ only

**Comment by TimPapler** [comment]
> @TimPapler the switch to SQLite will be 3.0+ only

I see, ok will have to migrate sooner then. When is 3.0 expected to be out of beta?

**Comment by jaredmixpanel** [comment]
@TimPapler The intention is to keep the version without Messages & Experiments as "beta" until M&E is fully deprecated. We will move it out of beta after we get some feedback, but that **won't** be before we have deprecated M&E in January 2022.

**Comment by zihejia** [comment]
Marking it closed now. Since 3.0.0 release is just around the corner(Jan 1, 2022) and we are encouraging everyone to try it out. We are fully supporting it! 

Reminder: On Jan 1, 2022, Messages & Experiments will be [removed](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/#:~:text=A%20year%20from%20now%2C%20on,offering%20discounts%20for%20getting%20started) from Mixapnel.
