### ISSUE TITLE
Automatic events like FirstAppOpen and AppUpdated is not tracked on second instance

### ISSUE THREAD

**Issue by andrey-krukovskiy** [mixpanel/mixpanel-swift#435]
Seems that second instance just reused user defaults values already altered by first instance
[MPFirstOpen](https://github.com/mixpanel/mixpanel-swift/blob/7a17d92a96dc027ac384b724ad7d75f9422ba6d0/Sources/AutomaticEvents.swift#L55)
[MPAppVersion](https://github.com/mixpanel/mixpanel-swift/blob/7a17d92a96dc027ac384b724ad7d75f9422ba6d0/Sources/AutomaticEvents.swift#L64)

I think there should be some label with apiToken...

**Comment by zihejia** [comment]
hi @andrey-krukovskiy , are you talking about multiple Mixpanel instances? why do you need `App First Open` and `App Version` to be different in different instances?

**Comment by andrey-krukovskiy** [comment]
Yes, it’s about mixpanel instances.
If I have two instances in the app, then these events are tracked only by instance which was created first. Second instance does not track it because values for these keys in nsuserdefaults already altered by first instance as I understand from code.

**Comment by jaredmixpanel** [comment]
hi @andrey-krukovskiy this issue is fixed in v2.9.2, thanks for the report.
