### ISSUE TITLE
Carthage error: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by Anders123fr** [mixpanel/mixpanel-swift#44]
The binary should be built with the newest version of Swift: 3.0.1

**Comment by nezhyborets** [comment]
Any updates? This issue have been persisting since October 26

**Comment by yarneo** [comment]
Will look into this today, thanks for the reminder and sorry for the delay

**Comment by yarneo** [comment]
Fixed in latest release!
