### ISSUE TITLE
Cannot build via Carthage after most recent mixpanel commit

### ISSUE THREAD

**Issue by King-Bahb** [mixpanel/mixpanel-swift#444]
From Terminal: `A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/mixpanel/mixpanel-swift.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/rkoning/Library/Caches/org.carthage.CarthageKit/dependencies/mixpanel-swift)) failed with exit code 1`

**Specifying an earlier version doesn't fix the issue. This was working fine as of 08:35a MST.

**Comment by zihejia** [comment]
hi @King-Bahb , are you saying it was working until today? Which version are you using?

**Comment by King-Bahb** [comment]
@zihejia It was compiling fine this morning using Carthage (v0.37.0). We weren't restricting the version, but the latest Cartfile.resolved shows v2.9.3. We tried to limit Carthage to until pull 2.9.3, but the same error occurs.

**Comment by zihejia** [comment]
We did not release anything new, Is there anything changed from Carthage's side?  I would suggest cleaning all the build and Carthage cache/reboot mac/change another machine, hope that helps.

**Comment by King-Bahb** [comment]
We had three developers try on different machines, to no avail. I've since imported this library using Swift Package Manager, and it appears to work. I'm fine with closing this issue.
