### ISSUE TITLE
Notification do not display image

### ISSUE THREAD

**Issue by mrkhanhkhi** [mixpanel/mixpanel-swift#445]
Hello guys,
I'm using the notification feature with image as config below:
<img width="1263" alt="Screen Shot 2021-05-12 at 16 05 58" src="https://user-images.githubusercontent.com/13785017/117949216-1532ea00-b33c-11eb-970f-39a929343a4a.png">

and the image URL from response: 
https://images.mxpnl.com/1310136/25a52ad0454315602d136b7595db0bbe.png

The notification was sent successful, but the image do not appear.  I also integrated the Notification Service Extension as the guide. The SDK version is 2.9.3.

Please help me check this issue. Thank you so much

**Comment by zihejia** [comment]
Hi @mrkhanhkhi , we are deprecating Messaging and Mobile A/B testing features(more details), please contact our support if you need to continue the conversation. Sorry for the inconvenience.
