### ISSUE TITLE
How to integrate mixpanel / firebase rich media notification parallel in NotificationService 

### ISSUE THREAD

**Issue by atifsaeed14** [mixpanel/mixpanel-swift#449]
How to integrate mixpanel / firebase rich media notification parallel in NotificationService facing the issue of both calling the same NotificationService file

// Mixpanel extent menthod
class NotificationService: MPNotificationServiceExtension { }

// Firebase extent menthod
class NotificationService: UNNotificationServiceExtension { }

Have any mixpanel method like firebase call on base of payload?
FIRMessagingExtensionHelper().populateNotificationContent(bestAttemptContent, withContentHandler: contentHandler)

**Comment by zihejia** [comment]
Hi @atifsaeed14 ,  we are deprecating Messaging and Mobile A/B testing features([more details)](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation. Sorry for the inconvenience.
