### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by AmbroiseCollon** [mixpanel/mixpanel-swift#45]
I've just updated to latest version of Xcode (8.0 => 8.1). Previously I had installed mixpanel-swift package with CocoaPods. It worked fine.

When I now build my project in Xcode 8.1, I get the following error :
```
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: 
```
I tried to rerun both `pod install` and `pod update`. It didn't solve the issue. What should I do ? Thanks !

**Comment by yarneo** [comment]
Hey @AmbroiseCollon, happy to help! 
Can you tell me which version of Mixpanel-swift are you using? We just recently sent out a new update ( v2.1.1 ) which should support Swift 3.0.1. 

If you have the latest version, could you try possible cleaning the project and rebuilding, and possibly cleaning out the Derived Data? It seems to be working on our end but could be an issue we are not aware of.

Also I would recommend updating to the latest Cocoapods version ( v1.1.1 )

**Comment by AmbroiseCollon** [comment]
I believe I had latest version. At least I do now. But I didn't thought of cleaning derived data which solved the issue. Thank you very much

**Comment by mxcl** [comment]
Every time Swift updates you must rebuild everything that is Swift or you get this error.
