### ISSUE TITLE
Build only Core files with SPM

### ISSUE THREAD

**Issue by antongaenko** [mixpanel/mixpanel-swift#470]
Hi guys, thank you for open source!

I want to use only base functionality of Mixpanel for tracking without swizzling and other additions to core classes. I checked that for Cocoapods you define supspec `Core`.

```
'Sources/Network.swift', 'Sources/FlushRequest.swift', 'Sources/PrintLogging.swift', 'Sources/FileLogging.swift',
    'Sources/Logger.swift', 'Sources/JSONHandler.swift', 'Sources/Error.swift', 'Sources/AutomaticProperties.swift',
    'Sources/Constants.swift', 'Sources/MixpanelType.swift', 'Sources/Mixpanel.swift', 'Sources/MixpanelInstance.swift',
    'Sources/Persistence.swift', 'Sources/Flush.swift','Sources/Track.swift', 'Sources/People.swift', 'Sources/AutomaticEvents.swift',
    'Sources/Group.swift',
    'Sources/ReadWriteLock.swift', 'Sources/SessionMetadata.swift'
```

Is any chance we can adopt something similar with SPM? If no, will everything work correctly if I just copy/paste these Core files into my sources.

Thanks!

**Comment by zihejia** [comment]
Hi @antongaenko , we have a `3.0.0.beta` branch that only contains core files. You can use SPM to point to that branch, it's in parity with the master branch, just without messaging and a/b testing features. I'm closing this one now, please feel free to open if you have more questions.

**Comment by antongaenko** [comment]
@zihejia that's cool! thank you for a quick answer
