### ISSUE TITLE
Crashes on iOS four finger Autotrack connection

### ISSUE THREAD

**Issue by niuguoning** [mixpanel/mixpanel-swift#48]
Looking at the stack trace, it looks like it start executing in a random part of my code, after running the mixpanel code.  I'm not sure if it's a compiler issue or something else.

Particularly, it looks like it's failing in getPropertyValue in ObjectSerializer.swift.  selectorDescription.selectorName is "preferredContentSize", which starts execution of UINavigationController.preferredContentSize, which eventually executes my code HomeownerViewController.viewDidLoad() which causes the crash.

![screen shot 2016-12-14 at 2 24 47 pm](https://cloud.githubusercontent.com/assets/2876152/21203823/42f8c4ce-c209-11e6-87b9-629848a6d093.png)

**Comment by yarneo** [comment]
thanks for the descriptive issue! I'll have a look at it and try to get back to you with a fix/explanation

**Comment by yarneo** [comment]
Hey @niuguoning , do you maybe know why it would crash in HomeownerViewController.viewDidLoad()? Or could maybe provide the fatalErrorMessage it provides? Thanks!

Also, is HomeOwnerViewController already visible or initialized when it is called?

**Comment by niuguoning** [comment]
Hi @yarneo , thanks for the quick feedback.  Still not sure what the exact issue was, but ended up fixing it by moving some code out of the app delegate function.

**Comment by rwinzhang** [comment]
Hello, @yarneo it looks like the crash is still happen on the `2.1.6`. It happens randomly when testing with four finger experiment.

<img width="1272" alt="screen shot 2017-05-24 at 5 59 06 pm" src="https://cloud.githubusercontent.com/assets/1652090/26400386/e57d3c32-40aa-11e7-8bae-c58feb2d3b34.png">

**Comment by yarneo** [comment]
hey @rwinzhang thanks for sending the screenshot! we are trying to reproduce it on our end to figure out the root cause. May I ask, if you initiate the 4 finger experiment on another screen, does it still crash?

If so, do you think you could provide a stripped down version of just that viewController so we can try and get it to crash for us? That would help us tremendously! 

Thanks!

**Comment by rwinzhang** [comment]
Hello @yarneo, I have tried to initiate the 4 finger experiment on another screen, and it is still crash. But now, I find it on another case again when I am typing on the textfield. Hope it useful.

<img width="1279" alt="screen shot 2017-05-30 at 11 37 50 am" src="https://cloud.githubusercontent.com/assets/1652090/26568419/61ed49ca-452d-11e7-931c-be6972d06beb.png">

**Comment by yarneo** [comment]
hey @rwinzhang this problem should now be fixed with the new release!
