### ISSUE TITLE
Unable to use Mixpanel-swift SPM package  in WatchKit Extension

### ISSUE THREAD

**Issue by dbyst** [mixpanel/mixpanel-swift#484]
Hi.

I would like to use Mixpanel on both iOS target and WatchKit Extension target.

It works fine with Cocoapods.

But I would like to use SPM.
And with SPM I have problems.
SPM package doesn't work fine in WatchKit Extension target.
Because project contains .xib files.
During project compile time I'm receiving next errors:

<img width="550" alt="Screenshot 2021-11-03 at 12 42 09" src="https://user-images.githubusercontent.com/5080130/140049844-0b42dde1-b4a7-4661-85d5-65565a1efe08.png">
<img width="1272" alt="Screenshot 2021-11-03 at 12 49 21" src="https://user-images.githubusercontent.com/5080130/140049854-0e27ee0d-52bb-4b4d-afd7-4b80d9c07b52.png">

**Comment by zihejia** [comment]
hi @dbyst , it is supported in `3.0.0.beta`, `3.0.0.beta.5` is in parity with v2.10.3 just without the Messages & Experiments feature supports. on Jan 1, 2022, we’ll remove the Messages & Experiments feature from Mixpanel([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)) and release 3.0.0. We have no plan to fix the SPM for WatchKit in 2.x.x. Sorry about the inconvenience.
