### ISSUE TITLE
Invalid Exclude for Info.plist file generates warning

### ISSUE THREAD

**Issue by OfftheCode** [mixpanel/mixpanel-swift#490]
## Overview

While using Mixpanel, as package dependency in Xcode. The warning appears that the Info.plist file is not found, and it's excluded in the `Package.swift` file:

```
exclude: [
                "Info.plist"
            ],
```

This is causing a warning in the project using Mixpanel dependency.

## Proposed solution
My guess is that the newest version was build with the Xcode 13.1 which is not generating `Info.plist` directly, therefore excluding it is not needed.

**Comment by zihejia** [comment]
hi @OfftheCode , I could not replicate the issue in Xcode 13.1, what is the warning message? Do you have a sample project?

**Comment by zihejia** [comment]
hi @OfftheCode , are you using Objective-C library or Swift?

**Comment by zihejia** [comment]
hi @OfftheCode , we moved `Info.plist` out of the Source directory and updated `Package.swift`, so the warning shouldn't be there anymore. Thank you for bringing it up.
