### ISSUE TITLE
Events timestamp precision

### ISSUE THREAD

**Issue by c128128** [mixpanel/mixpanel-swift#503]
Hi team,

I have already reported this via your web contact form.

Looks like your events time precision is 1 second, for that reason my events appear in your UI in a wrong order.

<img width="421" alt="Screen Shot 2022-01-16 at 3 34 35 PM" src="https://user-images.githubusercontent.com/69604865/149664433-58b07c03-a8cc-4b00-a81a-7feb8bae8eb3.png">

Must be:
* `FirstController (Appear)`
* `Session (Start)`
* `Version Installed (1.0.1)`

Xcode logs:
<img width="885" alt="Screen Shot 2022-01-16 at 3 36 58 PM" src="https://user-images.githubusercontent.com/69604865/149664507-f344c8ae-4064-4ad2-b937-b63b997bfe7c.png">

Not sure if this is only related to `mixpanel-swift` or your entire infrastructure only works within 1 second.

https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/Track.swift#L53-L60

**Comment by zihejia** [comment]
hi @c128128 , it's currently a backend limitation. But we are working on it now to improve it to the ms level. Please stay tuned. Since this is not an SDK issue, I'm closing this one now.

**Comment by kgaidis** [comment]
+1 on this, I wonder if this is tracked somewhere as it's so important for funnels; feel like funnels should have an asterisk until this is more precise

**Comment by jaredmixpanel** [comment]
@kgaidis it is not being tracked anywhere publicly, but it is still in active development.
