### ISSUE TITLE
@zihejia The `Automatically collect common mobile events` is off, and I think you have a race.

### ISSUE THREAD

**Issue by c128128** [mixpanel/mixpanel-swift#516]
@zihejia The `Automatically collect common mobile events` is off, and I think you have a race.

Ex:
1. I start the app.
2. `SDK` is doing request to get the `Automatically collect common mobile events` from server.
3. I record some events.
4. The result from request `2` is coming back.
5. `SDK` is deleting my recorded events.
6. I am missing events from `3`

_Originally posted by @c128128 in https://github.com/mixpanel/mixpanel-swift/issues/514#issuecomment-1033558798_

**Comment by zihejia** [comment]
using #514 to track
