### ISSUE TITLE
Xcode 8.2: Legacy Code Settings

### ISSUE THREAD

**Issue by mikeyLatch** [mixpanel/mixpanel-swift#52]
Issue to build with Xcode 8.2 because "Use legacy Swift Language Version" is undefined on the project build settings. I fixed by setting to "No"

**Comment by mikeyLatch** [comment]
I am on the most recent tag "2.1.1". I just realize, this issue there is just no release tag for fixing this issue, but it's fixed on the master branch.

**Comment by yarneo** [comment]
thanks ! I'll send out a new release today

**Comment by yarneo** [comment]
Fixed in newest release!
