### ISSUE TITLE
Deadlock during initialization on Mac SwiftUI

### ISSUE THREAD

**Issue by gabriellanata** [mixpanel/mixpanel-swift#524]
PR https://github.com/mixpanel/mixpanel-swift/pull/519 introduced a bug where the Mixpanel initialization code deadlocks on Mac M1 when using SwiftUI (possibly more, that's just the computer I was testing on).

Specifically [this code change](https://github.com/mixpanel/mixpanel-swift/pull/519/files#diff-150ed56746b70d75f34d9018dd4b1f766529e4ad8aad3a7c4d979678bd7cd3a4R162) that wraps the instance initialization in a dispatch queue and a semaphore. I've verified that by reverting that to the previous implementation the deadlock goes away.

Here is a sample SwiftUI project that reproduces the deadlock, you can try interacting with the window in any way (like resizing) and it will beachball forever.
[MixpanelDeadlock.zip](https://github.com/mixpanel/mixpanel-swift/files/8183750/MixpanelDeadlock.zip)

**Comment by gabriellanata** [comment]
I've submitted a PR with a suggested fix here: https://github.com/mixpanel/mixpanel-swift/pull/523

**Comment by gabriellanata** [comment]
cc @zihejia

**Comment by jaredmixpanel** [comment]
@gabriellanata this should be fixed in `v3.1.6`, let us know if any issues persist. thanks again!
