### ISSUE TITLE
App crashing after mixpanel integration on checkDecide

### ISSUE THREAD

**Issue by satanworker** [mixpanel/mixpanel-swift#532]
I've found old bug, but it supposed to be fixed already here
https://github.com/mixpanel/mixpanel-swift/pull/366/files
But yesterday in my app I saw the error message which looks suprisingly similar 
<img width="1305" alt="CleanShot 2022-03-29 at 14 42 22@2x" src="https://user-images.githubusercontent.com/11026240/160594478-967591cc-7695-4e7d-b1cf-3b35c5e82f96.png">
<img width="1274" alt="CleanShot 2022-03-29 at 14 43 46@2x" src="https://user-images.githubusercontent.com/11026240/160594558-fe283a3b-a20d-4db0-b820-029faf85bc17.png">
is there anything I can do? Using latest mixpanel with Swift PM

**Comment by jaredmixpanel** [comment]
@satanworker thanks for the report, will look into this and get back to you

**Comment by satanworker** [comment]
Let me know if I can assist somehow, unfortunately the issue is not consistent and happening from time to time :(

**Comment by jaredmixpanel** [comment]
@satanworker I was never able to reproduce the issue, but I put a fix in for my best guess as to what may have caused it. Can you please update to v3.2.1. and let me know if you still see the crash?

**Comment by jaredmixpanel** [comment]
closing for now, hopefully fixed in v3.2.1. please feel free to re-open if issue persists.
