### ISSUE TITLE
Using the prefix v in front of the version number makes Xcode and SPM unhappy

### ISSUE THREAD

**Issue by bonkowski** [mixpanel/mixpanel-swift#536]
This is because SPM expects only numbers in the semantic version number. 

_The minimum package version “v3.0.2“ is not a semantic version in the form of “1.2.3”_

**Comment by jaredmixpanel** [comment]
@bonkowski you can simply omit the "v" and just use "3.0.2"...

![image](https://user-images.githubusercontent.com/10504508/163019873-562413c8-1c6c-4fd8-bf8e-8bdfac037eaf.png)

**Comment by bonkowski** [comment]
🤦🏻‍♂️thanks
