### ISSUE TITLE
Mixpanel.initialize breaks my UI

### ISSUE THREAD

**Issue by btc** [mixpanel/mixpanel-swift#54]
When I initialize Mixpanel in my AppDelegate, I find that I am unable to drag one of my UI elements. Mixpanel breaks the UI. Since Mixpanel has nothing to do with UI, this shouldn't happen. Right now, I'm forced to disable Mixpanel on iOS.

I've narrowed down the issue to this line:

``` swift
        let mp = Mixpanel.initialize(token: "FOO")
```

This is an example project that reproduces the issue: https://github.com/btc/MixpanelLNPopupController/tree/master

**Comment by yarneo** [comment]
Hey @btc thanks for letting us know. We will update you this week once we have a potential fix. Thanks!

**Comment by yarneo** [comment]
also appreciate for making a sample app showing the problem, this is super helpful

**Comment by yarneo** [comment]
hey btc, i have pushed to master a fix for this issue. We are aware that there are a lot of implementations and 3rd party libraries that might conflict with the gesture recognizer that connects to our visual editor. Therefore we have a variable called enableVisualEditorForCodeless which can be set to false after initializing mixpanel. This will disable our gesture recognizer and fix your problem (works for the sample app you created too). I will send out a proper release for it this week. Thank you for your patience!

**Comment by btc** [comment]
Thank you. I'll try it out soon.

**Comment by yarneo** [comment]
this is now pushed in the latest release! thanks!
