### ISSUE TITLE
Potential SQL performance improvement

### ISSUE THREAD

**Issue by RamblinWreck77** [mixpanel/mixpanel-swift#585]
Version: 4.0.4

Seemed different enough from #584 to warrant its own issue, but I also noticed this in the disk report section:

<img width="237" alt="Screenshot 2023-02-06 at 2 00 16 PM" src="https://user-images.githubusercontent.com/22692130/217061125-f416e012-e315-4e36-9a91-bc596c9bd852.png">

Code:

<img width="1894" alt="Screenshot 2023-02-06 at 2 01 18 PM" src="https://user-images.githubusercontent.com/22692130/217061300-ec0f945c-14aa-478b-bdfb-ddba10531003.png">

**Comment by weibel** [comment]
On our app the disk write report shows that Mixpanel consumes in total 48% across several traces

**Comment by RamblinWreck77** [comment]
@zihejia This is the majority of our disk usage and we send a relatively small number of events. Could we potentially get this optimized in the next few weeks? Again I'm not an SQL expert but it _seems_ like adding an index is relatively straightforward?

**Comment by jaredmixpanel** [comment]
@RamblinWreck77 @weibel [The Apple docs](https://developer.apple.com/documentation/xcode/reducing-disk-writes) say...

> The Disk Writes Report pane suggestions identify queries that may benefit from an index.

> The Disk Writes Report pane suggests using write-ahead logging when a stack trace indicates a different journaling mode.

Are either of you seeing those suggestions or any others? I am going to look into this and see what we can do.

**Comment by jaredmixpanel** [comment]
@RamblinWreck77 @weibel I've released `v4.1.1` which adds index and enable WAL journaling mode. I'm going to close this for now. Feel free to re-open if the issue persists.

**Comment by RamblinWreck77** [comment]
@jaredmixpanel FWIW, this one update (mixpanel update was the only change) has reduced our disk writes MB/day to 1/5th the previous value
