### ISSUE TITLE
v4.0.5 compile error if installed using SPM

### ISSUE THREAD

**Issue by kientux** [mixpanel/mixpanel-swift#591]
In latest version update, some codes are updated to add `autoreleaseFrequency: .workItem` to DispatchQueue initialization. This param only available for iOS 10+, but `Package.swift` declares min iOS version is 9.0, so we cannot compile.

**Comment by zihejia** [comment]
hi @kientux , sorry for the inconvenience. Please try v4.0.6. I'm closing this one now, feel free to reopen if the problem exists.
