### ISSUE TITLE
Flush grows memory significantly until crash

### ISSUE THREAD

**Issue by thibauddavid** [mixpanel/mixpanel-swift#594]
Hi,

I'm using MixPanel 4.0.6.

When my share extension (which has a memory size limit) tries to flush, the memory grows until crashing.

It seems like `loadEntitiesInBatch` always uses a batchSize of Int.max, leading to `readRows` not using any limit for the SELECT query.
As a result, `rows.append(entity)` makes `rows` array growing unbounded.

I think `loadEntitiesInBatch` should be called in a paginated way for flushing to be memory-consistent.

**Comment by zihejia** [comment]
hi @thibauddavid , thanks for bringing it up. We will fix it.

**Comment by zihejia** [comment]
hi @thibauddavid, the fix is in 4.1.0. I'm closing this one now, feel free to reopen it if the problem exists. Thanks again!
