### ISSUE TITLE
Xcode 14.2 Swift Package Manager loops continuously when adding Mixpanel...

### ISSUE THREAD

**Issue by julestburt** [mixpanel/mixpanel-swift#599]
Adding either a specific version (2.10.x) or master branch causes a continuous spm update...removing mixpanel clone, installing mixpanel, checking all packages...removing mixpanel clone... etc

Error output is: invalid custom path 'Sources' for target 'Mixpanel'. Have 7 other SPM frameworks but no issues...

I checked over various 'paths' in Build Settings but everything appears to be on default?

Any suggestions? Thx.

**Comment by RamblinWreck77** [comment]
FWIW, I can't repro this on Xcode 14.3. Have you tried updating?

**Comment by RamblinWreck77** [comment]
Another trick is:
- Close Xcode
- nuke the "Derived Data" folder
- launch Xcode
- clean project
- See if SPM loads properly then (should automatically start refetching everything, but if not you can manually reset the package caches)

**Comment by julestburt** [comment]
Appreciate the comments. I'm about to upgrade to Ventura today, so I can get the latest Xcode to try it out. I did delete the entire derived data before posting here...sadly that didn't help. I'm able to add it to a new project no problem - just this older project has something odd about it. Will check back soon...with Ventura results.

**Comment by jaredmixpanel** [comment]
@julestburt I'm also not able to repro with Xcode 14.3 on Ventura. Are you still experiencing the issue?

**Comment by jaredmixpanel** [comment]
Closing this issue for now. Feel free to re-open if the issue persists.
