### ISSUE TITLE
Sometimes City is sent to Mixpanel even useIPAddressForGeoLocation is set as false.

### ISSUE THREAD

**Issue by ttmdung203** [mixpanel/mixpanel-swift#631]
The way I set `useIPAddressForGeoLocation`:
```
mixpanelInstance = Mixpanel.initialize(token: token, trackAutomaticEvents: true)
mixpanelInstance.delegate = self
mixpanelInstance.useIPAddressForGeoLocation = false

```

Even I check `useIPAddressForGeoLocation` at `mixpanelWillFlush`, the city is still sent:
```
 public func mixpanelWillFlush(_ mixpanel: MixpanelInstance) -> Bool {
       return !mixpanel.useIPAddressForGeoLocation
}
```
This issue is quite critical since it affects to my privacy document.
Prefer to move `delegate` & `useIPAddressForGeoLocation` to initialize function.
Thanks in advance.

**Comment by jaredmixpanel** [comment]
@ttmdung203 The SDK does not send geolocation info. When `useIPAddressForGeoLocation` is `true` the server will use the IP address to add geo info to the event after it is received. Make sure you're not manually setting a city property anywhere in your code. For further assistance please reach out to support@mixpanel.com

**Comment by ttmdung203** [comment]
Yes, I set `useIPAddressForGeoLocation = false` immediately as you see at below code, there's no manual city parameters  for sure.
```
mixpanelInstance = Mixpanel.initialize(token: token, trackAutomaticEvents: true)
mixpanelInstance.delegate = self
mixpanelInstance.useIPAddressForGeoLocation = false
``` 
It happens randomly, I was looking into source code and found that there is a chance of flushing events immediately right after `Mixpanel.initialize`, before I set `delegate` and  `useIPAddressForGeoLocation`. (Version: 4.2.0)

```
init(apiToken: String?, flushInterval: Double, name: String, trackAutomaticEvents: Bool, optOutTrackingByDefault: Bool = false,
         useUniqueDistinctId: Bool = false, superProperties: Properties? = nil,
         serverURL: String? = nil) {
....
....
 flushInstance.flushInterval = flushInterval
}
```

<img width="707" alt="Screenshot 2024-03-12 at 10 44 39 AM" src="https://github.com/mixpanel/mixpanel-swift/assets/12870242/0a3ff34f-912a-4b76-bbcb-3d1ef95dae17">

<img width="809" alt="Screenshot 2024-03-12 at 10 47 12 AM" src="https://github.com/mixpanel/mixpanel-swift/assets/12870242/772d9d35-d602-4158-85a8-4982df7c132f">

**Comment by jaredmixpanel** [comment]
@ttmdung203 That's not the correct way to initialize and use the Mixpanel instance. You don't need to store the instance. You should always use the shared instance provided by `Mixpanel.mainInstance()`:

```
Mixpanel.initialize(token: token, trackAutomaticEvents: true)
Mixpanel.mainInstance().delegate = self
Mixpanel.mainInstance().useIPAddressForGeoLocation = false
...
Mixpanel.mainInstance().track(event: "My Event")
```

Try that and let me know if it makes a difference.

**Comment by ttmdung203** [comment]
I've just tried the way you suggested, the city sometimes is sent to Mixpanel when I open app. 
####  Reproduce steps: 
* Open app and open some screens (to track screen viewed event), then close and open app again (to flush events automatically). 
* Repeat it until seeing the city in mixpanel. (It happens ~5-10% the time I do above steps).

````
Mixpanel.initialize(token: token, trackAutomaticEvents: true)
Mixpanel.mainInstance().useIPAddressForGeoLocation = false
Mixpanel.mainInstance().delegate = self

...
Mixpanel.mainInstance().track(event: "Event name")
```

**Comment by ttmdung203** [comment]
Thanks for your quick response, @jaredmixpanel 
I've just tried the way you suggested, the city sometimes is sent to Mixpanel when I open app. 
####  Reproduce steps: 
* Open app and open some screens (to track screen viewed event), then close and open app again (to flush events automatically). 
* Repeat it until seeing the city in mixpanel. (It happens ~5-10% the time I do above steps).

````
Mixpanel.initialize(token: token, trackAutomaticEvents: true)
Mixpanel.mainInstance().useIPAddressForGeoLocation = false
Mixpanel.mainInstance().delegate = self

...
Mixpanel.mainInstance().track(event: "Event name")
```
