### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by YTWhite9** [mixpanel/mixpanel-swift#637]
Hi,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file. Is there any plans to add a privacy manifest?
Please refer to this link: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks.

**Comment by jaredmixpanel** [comment]
@YTWhite9 yes, it is already supported in the latest version `v4.2.3`

**Comment by YTWhite9** [comment]
@jaredmixpanel Thanks for replying.

**Comment by alpennec** [comment]
Hello,

Can you please explain why you have not added any Privacy Nutrition Label Types to your manifest?
According to your [documentation](https://mixpanel.com/legal/app-store-privacy-details/), you collect data. These should be specified in your PrivacyInfo.plist file in the lib.

<img width="857" alt="image" src="https://github.com/mixpanel/mixpanel-swift/assets/2082662/63328b79-e78c-462c-97c9-def45a42cd59">

Thanks

**Comment by jaredmixpanel** [comment]
@alpennec All internal tracking has been removed from this SDK. Mixpanel does not collect any data via this SDK.
