### ISSUE TITLE
Is the mixpanel_flutter package using the latest (4.2.4) Mixpanel-swift pod?

### ISSUE THREAD

**Issue by AleedaGS** [mixpanel/mixpanel-swift#639]
I'm trying to get my cocoapods to update so I can pull the latest version of Mixpanel-swift (4.2.4) and be compliant with the privacy manifest requirement. Have upgraded to mixpanel_flutter 2.3.0 but cocopods is still insisting that I cannot update to the latest swift version. Is there something I am doing wrong or is the flutter package just not updated yet?

**Comment by jaredmixpanel** [comment]
https://github.com/mixpanel/mixpanel-flutter/blob/main/ios/mixpanel_flutter.podspec#L15
