### ISSUE TITLE
Remove automatic Integration event (has also been removed at the android library)

### ISSUE THREAD

**Issue by carstenhag** [mixpanel/mixpanel-swift#644]
See the discussion at https://github.com/mixpanel/mixpanel-android/issues/800 & PR at https://github.com/mixpanel/mixpanel-android/pull/835.

This library also still does it:

https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/MixpanelInstance.swift#L981-L999

Also see https://github.com/mixpanel/mixpanel-iphone/issues/1026

**Comment by zihejia** [comment]
Fixed in [4.2.7](https://github.com/mixpanel/mixpanel-swift/releases/tag/v4.2.7)
