### ISSUE TITLE
Event timestamps are tracked in seconds, not milliseconds

### ISSUE THREAD

**Issue by Stephan-Howey** [mixpanel/mixpanel-swift#648]
This line `rounds` the timestamp to Int which results in automatic Timestamp tracking in seconds, not milliseconds as the variable name and your documentation suggest: https://help.mixpanel.com/changelogs/2022-11-07-millisecond

I work around it by manually setting the "time" property for now as a Double.

https://github.com/mixpanel/mixpanel-swift/blob/e7869c433ee01cdc52aa14abf636fe0b412d72f8/Sources/Track.swift#L50

**Comment by jaredmixpanel** [comment]
`epochInterval` is a [TimeInterval](https://developer.apple.com/documentation/foundation/timeinterval) which is specified in seconds with sub-millisecond precision: https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/MixpanelInstance.swift#L1036

`* 1000` converts it to milliseconds and `round` drops the sub-millisecond precision.
