### ISSUE TITLE
Block default  swift properties 

### ISSUE THREAD

**Issue by vakhileshwar** [mixpanel/mixpanel-swift#649]
I am using Mixpanle Sdk -Swift , I have a requirement that I want to hide default properties/ Mixpanel properties
(Client do not want to see default properties in mixpanle board), is there any way to do it, please help me

Regards,
Akhileshwar Babu

**Comment by jaredmixpanel** [comment]
@vakhileshwar Properties can be hidden from within the Mixpanel.com web app: https://mixpanel.com/blog/now-you-can-hide-events-and-properties/

For further assistance please contact support@mixpanel.com
