### ISSUE TITLE
Would it be possible to have fine-grained controls on the geolocation tracking, to only include country for example?

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-swift#650]
Hello,

Mixpanel uses IP address to enrich events with geographic information like city, country, and region, and we can disable this setting.

I would like to have the possibility to disable only some fields like city and region.
I basically don't need region or city when I analyse my app usage, but I'm interested in having the country.

This is something Amplitude [does](https://amplitude.com/docs/sdks/analytics/ios/ios-swift-sdk#disable-tracking) which is really neat.

Can you consider adding an option to have fine-grained controls please?

Thanks

**Comment by jaredmixpanel** [comment]
@alpennec geolocation is performed on the server-side, based on the IP address of the API request from the client device. Feel free to reach out to support@mixpanel.com with this feature request and they will log it for you.
