### ISSUE TITLE
Overriding Mixpanel Default Properties

### ISSUE THREAD

**Issue by Cramsden** [mixpanel/mixpanel-swift#652]
We recently upgraded from the Objective C Mixpanel SDK to the Swift SDK. Our analytics team uses the default property ```mp_lib	Mixpanel Library	The Mixpanel library that sent the event.```
in order to determine if events are coming from the iOS app versus mobile web. 

This property was updated to be `swift` from `iPhone` when changing the Mixpanel library. Even though this change makes sense our analytics team has asked us to override this to be the old value `iPhone` so all events can be consistently grouped by one value instead of 2. Is there any way to do this? I have tried using `registerSuperProperties` which doesn't seem to override it at all and `registerSuperPropertiesOnce` which seems to override it some of the time. I have tried to override this property right after we initialize Mixpanel `Mixpanel.initialize`

**Comment by jaredmixpanel** [comment]
you should be able to override it via registering it as a super property or adding it to your `track()` calls. You can see the order in which the final properties object is constructed in the `track()` method...

[line 54 - initialized with automatic properties, this includes `mp_lib: swift`](https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/Track.swift#L54)

[line 74 - super properties are added, this should overwrite the values for any automatic property keys](https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/Track.swift#L74)

[line 76 - track call properties are added, this will overwrite any automatic properties or super properties](https://github.com/mixpanel/mixpanel-swift/blob/master/Sources/Track.swift#L76)

```
Mixpanel.initialize(token: "MIXPANEL_TOKEN", trackAutomaticEvents: trackAutomaticEvents)
Mixpanel.mainInstance().registerSuperProperties(["mp_lib": "iPhone"])
```

^ that should work - maybe you're calling `reset()` somewhere?

You could also create a "Custom Property" in Mixpanel to treat both as values as one: https://docs.mixpanel.com/docs/features/custom-properties

**Comment by Cramsden** [comment]
Thanks for your response @jaredmixpanel! We are registering this super property right after initialization in `willFinishLaunchingWithOptions` and we are not calling reset somewhere. We are still seeing some early events still come through with the "swift" value. Any thoughts on why this might be the case? 

Additionally, mostly we are using this value to distinguish between native app users and mobile web. Surely there is another way we can differentiate these users without using the mixpanel library field?

**Comment by jaredmixpanel** [comment]
@Cramsden Apologies I didn't catch this in my initial response... the fix here is to register the super properties in the initializer, avoiding the race condition you're seeing where some events get flushed before your call to   `registerSuperProperties()`.

`Mixpanel.initialize(token: "MIXPANEL_TOKEN", trackAutomaticEvents: trackAutomaticEvents, superProperties: ["mp_lib": "iPhone"])`

There are numerous default properties that exist on web that do not exist on mobile and vice versa. For example, the `$browser` property will be set for web events, it will not be set for mobile, similarly `$device` will be set on mobile events and will not be set for web. You could use the presence of those properties to distinguish between the platforms. The list of default properties is here: https://docs.mixpanel.com/docs/data-structure/property-reference/default-properties#client-side-sdks

Again, I would also call your attention to the "Custom Properties" feature in Mixpanel: https://docs.mixpanel.com/docs/features/custom-properties

For further assistance, please reach out to support@mixpanel.com
