### ISSUE TITLE
Crash in TakeoverNotificationViewController -> InAppButtonView -> UIColor(hex: 0x868686, alpha: 0.2)

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-swift#68]
Hello,

I am using Carthage 0.20 and the Mixpanel SDK v2.1.3.
I have a crash when the app wants to display a TakeOverNotification created on your dashboard.
I already have an extension for UIColor to create a color from an hex string in my app, so this is maybe the reason why I am having this crash.

![screenshot 2017-03-06 09 03 51](https://cloud.githubusercontent.com/assets/2082662/23601460/d406e892-024b-11e7-9cf9-5eb03fb00521.png)

Thanks,
Axel

**Comment by yarneo** [comment]
Hey @alpennec thanks for reporting this!
Is the method signature you have created, the exact same as the one we are using?
In any case, I should have a fix for you in the next day or so.

**Comment by alpennec** [comment]
Thanks @yarneo!
Here is my method:

```swift
/**
     Base initializer, it creates an instance of `UIColor` using an HEX string.
     - parameter hex: The base HEX string to create the color.
     - parameter alpha: The alpha to use for the color.
     */
    convenience init(hex: String, alpha: Double = 1.0) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int = UInt32()
        Scanner(string: hex).scanHexInt32(&int)
        let r, g, b: UInt32
        switch hex.characters.count {
        case 3: // RGB (12-bit)
            (r, g, b) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (r, g, b) = (int >> 16, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b) = (1, 1, 0)
        }
        self.init(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: CGFloat(255 * alpha) / 255)
    }
```

**Comment by yarneo** [comment]
Hey @alpennec I have pushed to master a fix for this. Please let me know if it works now. thanks!

**Comment by alpennec** [comment]
Hey @yarneo I just tested the master branch, it worked! I saw the TakeOverNotification without any crash. Thanks for the fix 😉.
