### ISSUE TITLE
App Transport Security for InAppNotification (http://cdn.mxpnl.com)

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-swift#69]
Hello,

I am using Carthage 0.20 and the Mixpanel SDK v2.1.3.
I don't understand why I receive this error message. I thought you were using https now.

![screenshot 2017-03-06 09 32 08](https://cloud.githubusercontent.com/assets/2082662/23602253/f8f1806e-024f-11e7-89d0-ea4068acab53.png)

Thanks,
Axel

**Comment by yarneo** [comment]
Thanks @alpennec , we are on this too :) We will update you on the progress.

**Comment by pchien** [comment]
Hi @alpennec. We've fixed this on the web side, so if you recreate your inapp notification now, it should work properly. We are also going to fix it for existing notifications, though that hasn't happened yet.

**Comment by pchien** [comment]
Just an update. It should be fixed for existing notifications now as well, so everything should just work for you now. @alpennec let us know if there's any issues!
