### ISSUE TITLE
Soft warning via compiler.

### ISSUE THREAD

**Issue by HackShitUp** [mixpanel/mixpanel-swift#7]
I run the code and it consistently issues the following: "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
Is it because mixpanel didn't include the binary into the framework?

**Comment by JackieQi** [comment]
@HackShitUp Yes, I don't think it's included. You need to install https://github.com/realm/SwiftLint#installation locally.

**Comment by HackShitUp** [comment]
@JackieQi Cool, thank you!

**Comment by yarneo** [comment]
Hey @HackShitUp , thanks @JackieQi for helping out! Yeah we decided to use SwiftLint so it can help us improve out codebase. If you don't wish to add SwiftLint, you can always remove the Run Script in the Mixpanel.xcodeproj under Build Phases. You will see there is only one Run Script there and it's to do with SwiftLint.
