### ISSUE TITLE
Can't update a user until the app is reinstalled

### ISSUE THREAD

**Issue by alpennec** [mixpanel/mixpanel-swift#70]
Hello,

I am using Carthage 0.20 and the Mixpanel SDK v2.1.4.
In my app, I am updating a user after I have identified him.

```swift
var mixpanelAttributes: Properties = ["$name": "Axel"]
Mixpanel.mainInstance().people.set(properties: mixpanelAttributes)
```

However, this does not seem to work: on the dashboard, I don't see the user (either created or updated). If I enable the logging in the Mixpanel SDK, I see that in the console.

<img width="802" alt="screenshot 2017-03-07 20 36 48" src="https://cloud.githubusercontent.com/assets/2082662/23674358/e96d9be2-0375-11e7-9d2f-c2cc7664096f.png">

I also tried, without success (same messages in the logs)

```swift
Mixpanel.mainInstance().people.set(property: "$name", to: "Axel")
```

If I remove my app from the device and reinstall it, I don't have the issue. I fear that if I update my app on the App Store, I can't track anymore the users.

Thanks,
Axel

**Comment by yarneo** [comment]
Hi Axel, are you sure you aren't passing in an object, either in a track call or a people set, which is not supported? Could you please make sure what objects you are sending to Mixpanel? If in fact the object was a string, it wouldn't have to enforce it like you see in the warning.
What you could do, is put a breakpoint where you get that warning and check out what object this is done on. Let me know what you find out

**Comment by alpennec** [comment]
Well, I just pasted the code I use to update my user. It is just a string
for the property called $name.
Also, as I told, if I remove the app from the device, and reinstall it, I
don't have the error (but the array I send as properties is unchanged
between before and after).

Axel

**Comment by alpennec** [comment]
Here is what I pass as a parameter:

<img width="1085" alt="screenshot 2017-03-07 22 24 07" src="https://cloud.githubusercontent.com/assets/2082662/23678532/cbccea5c-0384-11e7-8cb5-6724edb22f15.png">

I have that in the console

```swift
[Mixpanel - JSONHandler.swift - func makeObjectSerializable] (info) - enforcing string on object
```

**Comment by yarneo** [comment]
Thanks for providing that @alpennec ! Could you do me a favor and put this breakpoint:
<img width="884" alt="screen shot 2017-03-07 at 1 34 49 pm" src="https://cloud.githubusercontent.com/assets/4066863/23678955/f83e56ce-033a-11e7-86b1-e925c8c80571.png">
And tell me what the 'obj' parameter value is?

**Comment by alpennec** [comment]
Ok I'll try that tomorrow but it means I have to manually add the framework to my project right? (Instead of using Carthage).

Axel

**Comment by yarneo** [comment]
I'm afraid so! But if we find out what is the reason for the failure I'll make sure to send out a fix as soon as possible :) Appreciate your help on this

**Comment by yarneo** [comment]
Either manual integration or cocoapods should be good!

**Comment by alpennec** [comment]
Hey @yarneo I just tested, it seems to be when the property is a Bool... MixpanelType seems to support this kind of data type. From the SDK and documentation

```
Property keys must be String objects and the supported value types need to conform to MixpanelType. MixpanelType can be either String, Int, UInt, Double, Float, Bool, [MixpanelType], [String: MixpanelType], Date, URL, or NSNull.
```

Your method ```makeObjectSerializable``` does not check for a Bool type. Maybe this is the issue?

<img width="1342" alt="screenshot 2017-03-08 08 12 10" src="https://cloud.githubusercontent.com/assets/2082662/23693866/0e8b45d0-03d7-11e7-869e-defc18900559.png">

**Comment by yarneo** [comment]
Hey @alpennec , that should actually be fine! We convert the booleans to strings before sending them. do you get all these warnings only for boolean types?

**Comment by alpennec** [comment]
Hum strange. Yes, only for boolean. Can you try on your side?

**Comment by yarneo** [comment]
will do! it's pretty late here on the west coast so i'll update you in a couple of hours :) Thanks for helping with this.

**Comment by alpennec** [comment]
I performed a new test with the following dictionary:

```javascript
Printing description of :
▿ 15 elements
  ▿ 0 : 2 elements
    - .0 : "iOS Version History"
    - .1 : "3.2"
  ▿ 1 : 2 elements
    - .0 : "CloudKit Record Name"
    - .1 : "_04a2635012af2bae4a7d2bf67458922b"
  ▿ 2 : 2 elements
    - .0 : "$ios_app_release"
    - .1 : 3.2
  ▿ 3 : 2 elements
    - .0 : "$ios_version"
    - .1 : "10.2"
  ▿ 4 : 2 elements
    - .0 : "$swift_lib_version"
    - .1 : "2.1.4"
  ▿ 5 : 2 elements
    - .0 : "$last_name"
    - .1 : "jiji"
  ▿ 6 : 2 elements
    - .0 : "Language"
    - .1 : "français"
  ▿ 7 : 2 elements
    - .0 : "Locale Identifier"
    - .1 : "fr"
  ▿ 8 : 2 elements
    - .0 : "iOS Build History"
    - .1 : "341"
  ▿ 9 : 2 elements
    - .0 : "$ios_lib_version"
    - .1 : "2.1.4"
  ▿ 10 : 2 elements
    - .0 : "$first_name"
    - .1 : "dede"
  ▿ 11 : 2 elements
    - .0 : "$ios_app_version"
    - .1 : 341
  ▿ 12 : 2 elements
    - .0 : "$name"
    - .1 : "dede jiji"
  ▿ 13 : 2 elements
    - .0 : "$ios_device_model"
    - .1 : "x86_64"
  ▿ 14 : 2 elements
    - .0 : "Used Skipper before v2"
    - .1 : false
```

When ```makeObjectSerializable``` is called, I still have (Bool) in the ```obj``` parameter for the method and the selected case is default (then printing "enforcing string on object"). This is only happening for the "Used Skipper before v2" key with the value false (as you can see on the screenshot below).

![screenshot 2017-03-08 09 47 06](https://cloud.githubusercontent.com/assets/2082662/23696509/4101ec00-03e4-11e7-9539-571c1ffb511d.png)

The boolean value does not seems to be converted to a string before sending it.
I could not find where this conversion should be done. Can you provide the method?

**Comment by yarneo** [comment]
Hey @alpennec , just checked it out with a bool and it works well for me. However, I think making it default rather than checking for Bool is bad behavior in general. I will add the Bool case as it can also be serialized correctly without a need of conversion. Let me know what you find after the fix. If the issue still happens to you we can try to debug it more. Thanks!

**Comment by yarneo** [comment]
https://github.com/mixpanel/mixpanel-swift/commit/f62dc5c6d658ca612d831f57518a45748e6eac13

Here is the commit, let me know how it goes!

**Comment by alpennec** [comment]
Hey @yarneo thanks for the update. I tried again, I don't have the log anymore (and the breakpoint is not being hit!). So the issue seems to be fixed 👍🏻
