### ISSUE TITLE
Cannot run project after upgrading to 2.1.4

### ISSUE THREAD

**Issue by anfriis** [mixpanel/mixpanel-swift#71]
I upgraded the framework to 2.1.4 and received the new MixpanelAppex framework, but as I don't need to use it in my iOS project, I have not integrated that framework into my project. 

I have cleaned, and deleted build and derived data folder, but I receive the following error when running my project:
Found bundle at 

```
Found bundle at 
/Users/<redacted>/Library/Developer/CoreSimulator/Devices/
<redacted>/data/Library/Caches/com.apple.mobile.installd.staging/temp.mCZKl6/extracted/
<redacted>.app/Frameworks/MixpanelAppex.framework 
with the same identifier (com.mixpanel.Mixpanel) as bundle at
/Users/<redacted>/Library/Developer/CoreSimulator/Devices/
<redacted>/data/Library/Caches/com.apple.mobile.installd.staging/temp.mCZKl6/extracted/
<redacted>.app/Frameworks/Mixpanel.framework
```

**Comment by yarneo** [comment]
Hi @anfriis thanks for reaching out. Could you please provide me the integration method you are using to integrate Mixpanel. Also, could you please share if you are using the Mixpanel SDK for an iOS app or is it for tvOS/macOS/Appex. Thanks!

**Comment by anfriis** [comment]
HI @yarneo,
I use Carthage and only for iOS

**Comment by yarneo** [comment]
Hi @anfriis 
I am not able to reproduce an issue on my end.
Did you put in your Cartfile this: github "mixpanel/mixpanel-swift"
Did you put in your Linked Frameworks and Libraries only Mixpanel.framework (and not MixpanelAppex.framework)
Did you add a run script in the build phases with this as an input file: $(SRCROOT)/Carthage/Build/iOS/Mixpanel.framework

If this is the case, I would suggest to delete the carthage folder and re-run 'carthage update'. Also try running on a different simulator device. I wonder if it is to do with some weird simulator caching.

Thanks!

**Comment by anfriis** [comment]
Yes, I did all of the above.
But the problem occurs when updating from v2.1.3 to v2.1.4.

I have attached a new Xcode project with Mixpanel integration to prove my point.
It has a `Cartfile.resolved` with v2.1.3, so first try to build and run the project, and it should work fine.
Then run the `Carthage-Update-frameworks.command` to update all frameworks, and the framework should get updated to v2.1.4. Even though I clean, delete build folder etc., it is not possible to run the test project, because of the error stated above.

Try and see if you can get it to work in the test project :) 
[MixpanelTest.zip](https://github.com/mixpanel/mixpanel-swift/files/847127/MixpanelTest.zip)

**Comment by yarneo** [comment]
Thanks for sending the project! I followed the steps you provided (I couldn't test with v2.1.3 at first because the Carthage folder wasn't included so the compiled framework wasn't there). But I did run the command file and everything worked fine! Here is your sample project after issuing the command and Cartfile.resolved showing v2.1.4: [Mixpanel Sample Project](https://mixpanel.box.com/s/zo2s30r9jjh19dec2fgznqmtxus3rsa9)

**Comment by anfriis** [comment]
Yeah, but my problem was when having v2.1.3 and then upgrading to v2.1.4. 
The project size was too large with build folders included so had to omit them. But if you try to change the Cartfile.resolved to `github "mixpanel/mixpanel-swift" "v2.1.3"` and bootstrap that
and then call update to get the new version, see if you get the error.

But if other users like me, are upgrading to the new version from an earlier version, they might receive the same error as me.

Do you have any suggestions on how to clear the simulator caches?
I have tried to delete the app from my simulator, deleted build folder, cleaned derived data, but it still doesn't work

**Comment by yarneo** [comment]
Hi @anfriis , I did exactly the same steps you asked for and it worked fine. However, I did try to break it in certain ways and found that I get the same error if I add both the Mixpanel framework and the MixpanelAppex framework in the project.

Could you please do a search in your project and try to find if there is any place where MixpanelAppex is added, either in the run script or as a framework in a project? Also, check to see if you have one of your search paths of the project pointing recursively to the Carthage folder, which might cause to add both frameworks (Mixpanel and MixpanelAppex) to the same target

**Comment by anfriis** [comment]
Ahh that was it.
I am using the `carthage-copy-frameworks` script in the run script phase, to automatically add the input files for the frameworks. I thought that it only added frameworks from the Carthage `Build` folder that was actually linked to the project, but I can see that it also copied the `MixpanelAppex.framework`, and then it couldn't find the framework. 
To solve it, I just added the exclude parameter `--exclude MixpanelAppex.framework`

Thanks for your help!

**Comment by yarneo** [comment]
Awesome, glad you got it sorted!

**Comment by AJ9UNiDAYS** [comment]
Hi @anfriis @yarneo 

Could you confirm where you added the parameter `--exclude MixpanelAppex.framework`, using Mixpanel for this first time and I have also encountered the same problem!

**Comment by anfriis** [comment]
Look here (i also exclude Fabric and Crashlytics here): 
<img width="1850" alt="skaermbillede 2017-05-17 16 08 52" src="https://cloud.githubusercontent.com/assets/1019341/26158109/27335c28-3b1b-11e7-8ce3-16dd2d66dbe2.png">

**Comment by AJ9UNiDAYS** [comment]
So for @yarneo / Mixpanels benefit, using pure carthage and the default copy-frameworks will mean Mixpanel will not work 👍

**Comment by yarneo** [comment]
Hey @AJ9UNiDAYS , if you have an issue with integrating the library please let us know so we can try and fix any arising issues. We are here to help, thanks!
