### ISSUE TITLE
Cache files location for non-sandboxed macOS apps.

### ISSUE THREAD

**Issue by Krivoblotsky** [mixpanel/mixpanel-swift#73]
I've found out that Mixpanel stores its cache files to the _~/Library/Caches_ folder which is not the best location. It suits sandboxed apps because of their Containers, but I suggest to change the path to _~/Library/Caches/<bundle_id>/_ to avoid possible issues. 

![312](https://cloud.githubusercontent.com/assets/1411778/24070714/6fea01b2-0bcb-11e7-8001-8da75bd62824.png)

What do you think? I can submit a PR once you agree.

**Comment by yarneo** [comment]
Hey @Krivoblotsky , may I ask which platform you are using Mixpanel for? When I checked, I noticed that we put it in the Caches directory only if it's non iOS (see here: https://github.com/mixpanel/mixpanel-swift/blob/master/Mixpanel/Persistence.swift#L44 )

If you think there is a better placement, you are very welcome to open a PR! Thanks!
