### ISSUE TITLE
A/B developer tweaks not working

### ISSUE THREAD

**Issue by AshishIOS007** [mixpanel/mixpanel-swift#74]
Hello 

After connect my iPhone to mixpanle it will update the tweaks variables value instant in same phone but its not updating in other device even after kill the application.

Thanks

**Comment by ninjudd** [comment]
I am having the same issue. I'll forward a link to this issue to Mixpanel support.

**Comment by wgins** [comment]
Hi @ninjudd -- the issue you're referencing is likely due to /decide API [downtime](https://status.mixpanel.com/). Could you try again and let me know if the issue persists?

@AshishIOS007 Are you calling the identify method? After calling the identify method make sure you're backgrounding and foregrounding the app to ensure the A/B test applies. If you'd like to override the default behavior of the SDK please reference [this post](https://mixpanel.com/help/questions/articles/how-can-i-effectively-ab-test-the-very-first-screen-or-sign_up-flow-of-my-app).

**Comment by ninjudd** [comment]
I'm still having the issue even after the API fixes. I'm on Mixpanel-swift (2.1.4). Is that the latest version?

Here is what I see in the logs when I do `Mixpanel.mainInstance().loggingEnabled = true`:
```
[Mixpanel - MixpanelInstance.swift - func loggingEnabled] (info) - Logging Enabled
Permission granted.
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (debug) - codeless event bindings check response format error
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (debug) - variants check response format error
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new codeless bindings out of []
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new variants out of []
```

FWIW, switching back to the Objective-C SDK fixes the issue.

**Comment by wgins** [comment]
For posterity, from the logs above we saw "variants check response format error". This error was thrown in response to the SDK receiving tweaks from an A/B test generated with the Mixpanel Obj-C library. A/B tests created in the Obj-C library are not compatible with those created in the Swift SDK and vice versa.

**Comment by AshishIOS007** [comment]
**@wgins**  Yeah, I am using identify method and also enabled log and its look like same as @ninjudd given.

**Comment by yarneo** [comment]
@ninjudd @AshishIOS007 could you please check if the A/B tests were created using the objective-c SDK initially? If this is the case, please contact support@mixpanel.com and let us know and we can have a look at the specific A/B test and help resolve the issue. As a fix for now, please create the test using this SDK. Thanks!

**Comment by jonchui** [comment]
FYI, i'm having trouble with the dev tweaks working on our swift project (event tracking works, so i know it's talking to the library). 

I too am seeing these errors when i turn on logging:

```
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (debug) - codeless event bindings check response format error
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 available notifications out of 0 total
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new codeless bindings out of []
[Mixpanel - Decide.swift - func checkDecide(forceFetch:distinctId:token:completion:)] (info) - decide check found 0 new variants out of [<Mixpanel.Variant: 0x60c00005e6c0>]
```

I filed https://github.com/mixpanel/mixpanel-swift/issues/223 to track my issue
