### ISSUE TITLE
Xcode 8.3 Compatibility

### ISSUE THREAD

**Issue by freak4pc** [mixpanel/mixpanel-swift#78]
It seems the MixPanel SDK wasn't properly prepared for Xcode 8.3, despite the fact there were 5 betas before release. 

![image](https://cloud.githubusercontent.com/assets/605076/24452928/694ab196-148e-11e7-8bdb-487bba04ad9c.png)

If you accept PRs I don't mind fixing it real quick. I've already fixed locally for the time being to clean up the warnings.

Thanks :)
Shai

**Comment by dfmuir** [comment]
+1

**Comment by yarneo** [comment]
Thanks Shai. We will send out a release today.

**Comment by freak4pc** [comment]
Much appreciated :) thanks @yarneo

**Comment by yarneo** [comment]
[Release v2.1.5](https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.1.5) is out with support for Xcode 8.3. Thanks!

**Comment by freak4pc** [comment]
Gotta love such a fast turnover ! 
💯 for promptness :)
