### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by ikzjfr0** [mixpanel/mixpanel-swift#80]
I use Carthage (0.20.1):
`github "mixpanel/mixpanel-swift" ~> 2.1.5`

and run
`carthage update --platform iOS --no-use-binaries`
(no error/warning message to run this command)

and clean folder of /Users/ouou/Library/Developer/Xcode/DerivedData
and clean project in Xcode

Then I got following compiling error on Xcode 8.3

<unknown>:0: error: module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Users/ouou/Documents/Project/epc-ios/Carthage/Build/iOS/Mixpanel.framework/Modules/Mixpanel.swiftmodule/x86_64.swiftmodule

**Comment by love4maon** [comment]
are you already solved this problem?  i have same problem now.

**Comment by yarneo** [comment]
Thanks guys, we tried reproducing it on our end but were not able to. @love4maon did you also issue the `carthage update  --platform iOS --no-use-binaries` command with the `--no-use-binaries`?

If all fails, I suggest updating to Carthage release 0.20: https://github.com/Carthage/Carthage/releases/tag/0.20.0 
Which now uses the prebuilt binary only when it used the same Swift compiler version: `Pre-built Swift binaries will only be used if they were built with the same version of the Swift compiler`

**Comment by yarneo** [comment]
Feel free to reopen this issue if you need more help in solving this issue. Thanks!
