### ISSUE TITLE
Mixpanel Tweaks Persist after 4-finger Connect if Cancel Experiment

### ISSUE THREAD

**Issue by blieber** [mixpanel/mixpanel-swift#82]
Repro steps:
1. Create new experiment
2. Connect app to experiment e.g. using 4-finger UI
3. Change a tweak
4. Cancel experiment
-- tweaks set using 4-finger UI persist indefinitely for app

**Comment by yarneo** [comment]
Hey @blieber , can you please share what kind of tweak you tried to alter and if it persists after relaunching the app? I tried doing the steps you mentioned and the tweaks seem to go back to their original settings if I press cancel without saving the changes.

**Comment by yarneo** [comment]
Hey @blieber are you still witnessing this? Thanks

**Comment by pchien** [comment]
Ah we fixed something related to this recently https://github.com/mixpanel/mixpanel-swift/pull/157. @blieber feel free to reopen if this is still an issue for you.
