### ISSUE TITLE
Support for Swift 4 / Xcode 9

### ISSUE THREAD

**Issue by mayurdzk** [mixpanel/mixpanel-swift#93]
Hello,

I wanted to know if Mixpanel is working on supporting the SDK for Xcode 9 Beta 1 / Swift 4 and if there is existing code that I could use with my Swift 4 project.
(I've tried looking at the branches in the mixpanel-swift project and I couldn't find one that indicated support for these environments)

**Comment by yarneo** [comment]
hey @mayurdzk,

We are currently working on providing support for Swift 4 and should have something fairly soon.
Will provide an update once we open up the branch.

Thanks!

**Comment by ikzjfr0** [comment]
looking forward it too :)

**Comment by ikzjfr0** [comment]
do you have a estimated release date? I'm testing on Xcode9 and found it's broken when "carthage update"

**Comment by mayurdzk** [comment]
@yarneo  Thank you very much and all the best!

**Comment by yarneo** [comment]
we now have Swift 4 support! You can find it in our swift4 branch: https://github.com/mixpanel/mixpanel-swift/tree/swift4

**Comment by TTNNehaJain** [comment]
Even after updating the pod Mixpanel show errors related to Swift 4

**Comment by levibostian** [comment]
@TTNNehaJain you need to install Mixpanel on Cocoapods via the swift4 branch:

```
pod 'Mixpanel-swift', :git=> 'https://github.com/mixpanel/mixpanel-swift.git', :branch=> 'swift4'
```

Put that in your Podfile.
