### ISSUE TITLE
In-app notifiction openURL throws NSInvalidArguemntException, crashes app

### ISSUE THREAD

**Issue by gleuch** [mixpanel/mixpanel-swift#94]
**What is wrong?**
Seems like there's a few bits wrong with `Mixpanel/InAppNotifications.swift` with recent change to `openURL` around line 94.

**Error given**
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication openURL]: unrecognized selector sent to instance 0x7ff96a602a50'`

**Details**
First, it seems that the selector from string needs to be suffixed with a colon. I was unable to get any links to open until I appended a colon to `NSSelectorFromString("openURL:")`.

After the change, the rest of the line throws EXC_BAD_ACCESS. (Maybe something on our end?)

I'm pretty new to Swift, so I could be a bit wrong? :shrug: Suggestions welcomed!

Full debug output below.

```
2017-06-20 19:58:36.606 Poncho[54484:4571230] -[UIApplication openURL]: unrecognized selector sent to instance 0x7f867ac026d0
2017-06-20 19:58:36.638 Poncho[54484:4571230] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication openURL]: unrecognized selector sent to instance 0x7f867ac026d0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107311b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010695c141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107381134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000107298840 ___forwarding___ + 1024
	4   CoreFoundation                      0x00000001072983b8 _CF_forwarding_prep_0 + 120
	5   Mixpanel                            0x00000001059fcea1 _TFFC8Mixpanel18InAppNotifications25notificationShouldDismissFT10controllerCS_30BaseNotificationViewController15callToActionURLGSqV10Foundation3URL__SbU0_FT_T_ + 561
	6   Mixpanel                            0x0000000105a12acc _TFFC8Mixpanel30MiniNotificationViewController4hideFT8animatedSb10completionFT_T__T_U0_FSbT_ + 492
	7   Mixpanel                            0x0000000105a120e3 _TTRXFo_dSb__XFdCb_dSb__ + 51
	8   UIKit                               0x0000000108523cd4 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 527
	9   UIKit                               0x00000001084f6f07 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 222
	10  UIKit                               0x00000001084f7446 -[UIViewAnimationState animationDidStop:finished:] + 136
	11  QuartzCore                          0x000000010818368e _ZN2CA5Layer23run_animation_callbacksEPv + 306
	12  libdispatch.dylib                   0x000000010b63605c _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010b61740b _dispatch_main_queue_callback_4CF + 411
	14  CoreFoundation                      0x00000001072d6909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	15  CoreFoundation                      0x000000010729cae4 __CFRunLoopRun + 2164
	16  CoreFoundation                      0x000000010729c016 CFRunLoopRunSpecific + 406
	17  GraphicsServices                    0x000000010f3f9a24 GSEventRunModal + 62
	18  UIKit                               0x000000010846b0d4 UIApplicationMain + 159
	19  Poncho                              0x0000000104e13de7 main + 55
	20  libdyld.dylib                       0x000000010b68265d start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by mxcl** [comment]
This is with latest: 2.1.7

**Comment by mxcl** [comment]
I guess because it is deprecated? https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl

Seems unexpected though, it's deprecated but *not* gone. We build against iOS 10.

**Comment by yarneo** [comment]
Thanks for writing in @gleuch! This is indeed an issue. I think the reason we are getting an EXC_BAD_ACCESS is because it isn't called from the main thread.
I noticed that calling `MixpanelInstance.sharedUIApplication()?.performSelector(onMainThread: NSSelectorFromString("openURL:"), with: callToActionURL, waitUntilDone: true)` works fine (feel free to test it and make sure on your end). However the problem with this method is that it doesn't give back a return value so I will need to revisit and see how to improve this. I will make sure to send out a new release first thing tomorrow that should fix this issue.

**Comment by yarneo** [comment]
I'm pushing out a new release with the proposed fix ^ @gleuch can you do me a favor and see if this resolves the issue on your end? I pushed it already to master, but want to make sure this is the best solution.

**Comment by gleuch** [comment]
@yarneo Indeed, that seems to work without crashes or errors. Thanks for quick fix.

**Comment by EugeneGoloboyar** [comment]
Is this resolved?
Because I've found this crash too with Mixpanel?
Does the latest SDK (in Cocoa Pods) have this fix?

**Comment by mxcl** [comment]
I do not represent the project, but if you need it urgently then I suggest applying the suggested fix directly to the sources and submitting. This means your version control won't contain the fix but urgent times dictate urgent actions.

**Comment by yarneo** [comment]
@gleuce @EugeneGoloboyar @mxcl a new release has just been sent out with the proposed fix: https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.1.8
